### ISSUE TITLE
dnsdist: setTagAction and setTagResponseAction should update existing tags

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#10603]
- Program: dnsdist 
 - Issue type: Bug report

### Short description
As reported in #10601, the current behaviour of `setTagAction` and `setTagResponseAction`, not overwriting existing tag values if any, is quite unexpected. We should likely change that.

**Comment by steffann** [comment]
It might make sense to add an `overwrite` or `force` optional parameter to `setTagAction` and `setTagResponseAction` which is false by default, so that people relying on the current behaviour don't get nasty surprises.

Also: adding a `clearTagAction` and `clearTagResponseAction` might be useful :)

And of course keep `DNSQuestion` and `DNSResponse` in sync, because they exhibit the same behaviour as the Actions.
