### ISSUE TITLE
Allow falling back to using authoritatives if forwarders respond with servfail 

### ISSUE THREAD

**Issue by ctheune** [PowerDNS/pdns#10690]
- Program: Recursor
 - Issue type: Feature request

### Short description

I'd like to be able to instruct pdns_resolver to do a regular authoritative lookup "dance" if none of the (recursive) forwarders respond. 

### Usecase

In our setups (data center for VMs as well as our own home networks) we typically deploy resolver configuration by running a local recursor and trying to delegate upstream to services like Quad9.

In the past we have been burned by either operators of authoritative servers accidentally blocking our networks due to typos and not having NOCs reachable around the clock, but we have also been burned by caching services like Quad9 having issues.

After a bit of back and forth we are currently running bind servers that forward with the "forward first" strategy: if the forwarder responds with a servfail the local resolver will fall back trying to talk to the authoritative directly.

### Description

I'm currently debugging some issues in my home network where I'm trying to get a similar configuration running with pdns_recursor but I think the knob for "when I run out of forwarders, just do the regular dance to talk to the authoritative" is missing. I _think_ I could cobble this together by running a second pdns_recursor as a second forwarder, but this seems dirty. 

Looking at the archive I found very little discussion about this except a short exchange back in 2013 and the issue tracker was similarly quiet.

I might be completely missing something obvious, but maybe not ... :)

**Comment by ctheune** [comment]
Here's an example of a forward that ended up in a SERVFAIL for the client because the recursive forwarder gave us a servfail:

```
Sep 04 07:27:34 cecil pdns_recursor[153731]: 3 [18/1] question for 'ligabank.de|A' from 192.168.2.228:53395
Sep 04 07:27:35 cecil pdns_recursor[153731]: : no TA found for 'ligabank.de' among 1
Sep 04 07:27:35 cecil pdns_recursor[153731]: : no TA found for 'de' among 1
Sep 04 07:27:35 cecil pdns_recursor[153731]: : got TA for '.'
Sep 04 07:27:35 cecil pdns_recursor[153731]: ligabank.de: Wants DNSSEC processing, auth data in query for A
Sep 04 07:27:35 cecil pdns_recursor[153731]: ligabank.de: No cache hit for 'ligabank.de|A', trying to find an appropriate NS record
Sep 04 07:27:35 cecil pdns_recursor[153731]: ligabank.de: Cache consultations done, have 1 NS to contact
Sep 04 07:27:35 cecil pdns_recursor[153731]: ligabank.de: Domain has hardcoded nameserver
Sep 04 07:27:35 cecil pdns_recursor[153731]: ligabank.de.: Nameservers: +9.9.9.11:53(13.25ms)
Sep 04 07:27:35 cecil pdns_recursor[153731]: ligabank.de: Resolved '.' NS (empty) to: 9.9.9.11
Sep 04 07:27:35 cecil pdns_recursor[153731]: ligabank.de: Trying IP 9.9.9.11:53, asking 'ligabank.de|A'
Sep 04 07:27:35 cecil pdns_recursor[153731]: ligabank.de: (empty) (9.9.9.11) returned a Server Failure, trying sibling IP or NS
Sep 04 07:27:35 cecil pdns_recursor[153731]: ligabank.de: Failed to resolve via any of the 1 offered NS at level '.'
Sep 04 07:27:35 cecil pdns_recursor[153731]: ligabank.de: failed (res=-1)
Sep 04 07:27:35 cecil pdns_recursor[153731]: 3 [18/1] answer to question 'ligabank.de|A': 0 answers, 1 additional, took 1 packets, 271.452 netw ms, 271.601 tot ms, 0 throttled, 0 timeouts, 0 tcp connections, rcode=2, dnssec=Indeterminate
```

**Comment by ctheune** [comment]
I've continued digging around (and yes, adding more resolvers obviously helps working around for now) and stumbled over another interesting aspect: I try to use ECS-supporting forwarders to help graybox that decide based on geolocation about the closest point and also avoid issues with services like Netflix where I would end up in the wrong catalog based on the IP. 

So, an extension of this feature could/would/be to allow configuring a preferential order of forwarders so that I could say: "first try getting a response from those 3 (that support ECS), if that doesn't work try one of those 3 (that are still privacy enabled but do not support ECS), and if none of those work, then just do the resolver yourselve)".

This is something I currently can't build even when adding a chain of forwarders because the selection is AFAICT more or less random and if I read things correctly with a bias based on the forwarders performance. This is also the indicator that my idea of adding a second forwarder that just does the authoritative dance isn't helpful because it would not get selected based on preference but performance/chance.

**Comment by phonedph1** [comment]
My opinion is that the interaction of forward zones with existing features can be problematic enough (dnssec, root-nx-trust, etc) that this idea at first glance doesn't seem like a good idea to add another layer on.

**Comment by johnhtodd** [comment]
What you're talking about looks a lot like what could be accomplished with some of the dnsdist ideas contained in https://github.com/PowerDNS/pdns/issues/6181

**Comment by ctheune** [comment]
Thanks for the feedback and for the pointer to #6181. I don't see a way to contribute to this at the moment, but I agree with the person reporting #6181 and with my current experience about the DNS reality on the internet I guess I won't be able to run pdns_recursor in my settings at all as I would face a similar situation as the colleague over there that I'd be loosing customers pretty quickly. 

Let me know if there is something I can contribute.

**Comment by johnhtodd** [comment]
The way to solve your specific problem possibly could be to set up dnsdist as your ingestion point from clients and point to a list of "quad9-like" forwarders  (I might be slightly biased) as well as your own recursive resolver as a lowest-priority member of the pool. dnsdist will detect if one forwarder is down or slow due to any cause, and will automatically shed/share load to other forwarders.  This is highly configurable with dnsdist, and possibly is a good way to handle what you want to do. For some us, this isn't the right solution (because of servfail or timeout results from authoritative servers in ways that can't be avoided) but thought I'd at least mention it. The problem is if you get a "servfail" or "nxdomain" or "refused" result from the forwarder; you're kind of out of options - a valid answer ends the process, period. Timeouts - different story entirely.

**Comment by ctheune** [comment]
Thanks for the detail - I appreciate that!

However, I'd like to disagree with the notion that "servfail" is a valid answer. Our experience shows that we regularly get practical issues both temporary (which maybe hours or days) failures of operators of authoritative servers as well as failures from quads with specific zones. I (and I think the RFC agrees with me here) considers SERVFAIL an indicator to go looking for other sources. I mean - we do set up multiple authoritatives just because we want to be able to *fail* over to other servers in case that something went wrong.

Specifically looking at RFC 1035 2.1:

> Resolvers are responsible for dealing with the distribution of
the domain space and dealing with the effects of name server failure by
consulting redundant databases in other servers.

Looking at page 27:

> Server failure - The name server was
                                unable to process this query due to a
                                problem with the name server.

From neither of those I get the impression that "servfail" is a valid answer that should end the process.

Care to explain what I'm missing?

**Comment by johnhtodd** [comment]
Hey, I agree with you.  :-)  I'm an advocate of being able to cascade through forwarders in the event of servfail - see #6181. I'll let someone else with more photographic memory answer as to why SERVFAIL should be treated as a stop point - the relevant RFCs are getting to be quite a pile to print out. Maybe it is an opinion and not a "MUST".

**Comment by ctheune** [comment]
Happy to dig through the RFC pile. I'm aware that I just pulled out the original one and might be missing something that came later.

I'm going through the "updated by" references from the original and am attaching all findings of "servfail" and "server failure". I have not been able to completely consume all the RFCs yet, so this might be a bit piecemeal right now. I agree with you that maybe it needs to be an option and not a MUST. I haven't seen anything that makes it a "MUST NOT".

https://datatracker.ietf.org/doc/html/rfc2136#section-2

> [...]
>               SERVFAIL    2       The name server encountered an internal
>                                  failure while processing this request,
>                                  for example an operating system error
>                                 or a forwarding timeout.

...

>    3.4.2.1. If any system failure (such as an out of memory condition,
>   or a hardware error in persistent storage) occurs during the
>   processing of this section, signal SERVFAIL to the requestor and undo
>   all updates applied to the zone during this transaction.

...

>    4.5. If the requestor receives a response, and the response has an
>   RCODE other than SERVFAIL or NOTIMP, then the requestor returns an
>   appropriate response to its caller.

>   4.6. If a response is received whose RCODE is SERVFAIL or NOTIMP, or
>   if no response is received within an implementation dependent timeout
>   period, or if an ICMP error is received indicating that the server's
>   port is unreachable, then the requestor will delete the unusable
>   server from its internal name server list and try the next one,
>   repeating until the name server list is empty.  If the requestor runs
>   out of servers to try, an appropriate error will be returned to the
>   requestor's caller.

https://datatracker.ietf.org/doc/html/rfc2308#section-2.1.1

> [...]
>    Some resolvers incorrectly continue processing if the authoritative
>   answer flag is not set, looping until the query retry threshold is
>   exceeded and then returning SERVFAIL.  This is a problem when your
>   nameserver is listed as a FORWARDER for such resolvers.  If the
>   nameserver is used as a FORWARDER by such resolver, the authority
>   flag will have to be forced on for NXDOMAIN responses to these
>   resolvers.  In practice this causes no problems even if turned on
>   always, and has been the default behaviour in BIND from 4.9.3
>   onwards.

https://datatracker.ietf.org/doc/html/rfc2308#section-7.1

> Server failures fall into two major classes.  The first is where a
>   server can determine that it has been misconfigured for a zone.  This
>   may be where it has been listed as a server, but not configured to be
>   a server for the zone, or where it has been configured to be a server
>   for the zone, but cannot obtain the zone data for some reason.  This
>   can occur either because the zone file does not exist or contains
>   errors, or because another server from which the zone should have
>   been available either did not respond or was unable or unwilling to
>   supply the zone.
>   The second class is where the server needs to obtain an answer from
>   elsewhere, but is unable to do so, due to network failures, other
>   servers that don't reply, or return server failure errors, or
>   similar.
>
>   In either case a resolver MAY cache a server failure response.  If it
>   does so it MUST NOT cache it for longer than five (5) minutes, and it
>   MUST be cached against the specific query tuple <query name, type,
>   class, server IP address>.

https://datatracker.ietf.org/doc/html/rfc4033#section-5

>    The specification in this document set defines the behavior for zone
>   signers and security-aware name servers and resolvers in such a way
>   that the validating entities can unambiguously determine the state of
>   the data.
> [...]
>   This specification only defines how security-aware name servers can
>   signal non-validating stub resolvers that data was found to be bogus
>   (using RCODE=2, "Server Failure"; see [RFC4035]).

https://datatracker.ietf.org/doc/html/rfc4035#section-3.2.2

> [...]
>    If the resolver side implements a BAD cache (see Section 4.7) and the
>   name server side receives a query that matches an entry in the
>   resolver side's BAD cache, the name server side's response depends on
>   the state of the CD bit in the original query.  If the CD bit is set,
>   the name server side SHOULD return the data from the BAD cache; if
>   the CD bit is not set, the name server side MUST return RCODE 2
>   (server failure).

https://datatracker.ietf.org/doc/html/rfc8490#section-5.4.1

> [...]
>     2 | SERVFAIL  | Server failed to process DSO request message   |
   |      |           | due to a problem with the server               |

https://datatracker.ietf.org/doc/html/rfc8490#section-7.2.1

> [...]
>  o  SERVFAIL indicates that the server is overloaded due to resource
      exhaustion and needs to shed load.

https://datatracker.ietf.org/doc/html/rfc8767#section-6

> [...]
>    The directive in Section 4 that only NoError and NXDomain responses
>   should invalidate any previously associated answer stems from the
>   fact that no other RCODEs that a resolver normally encounters make
>   any assertions regarding the name in the question or any data
>   associated with it.  This comports with existing resolver behavior
>   where a failed lookup (say, during prefetching) doesn't impact the
>   existing cache state.  Some authoritative server operators have said
>   that they would prefer stale answers to be used in the event that
>   their servers are responding with errors like ServFail instead of
>   giving true authoritative answers.  Implementers MAY decide to return
>   stale answers in this situation.

**Comment by gelin** [comment]
Hm... I want something opposite... With our Recursor installation we discovered that authoritative lookup may fail if there are some local network connectivity issues (for example, last time it was loss of IPv6 connectivity). But lookup through Cloudflare or Google DNS from the same location successes.
So, I want a "backup forwarders". If authoritative lookup fails, try to forward to some other DNS servers in hope they can resolve the domain.

**Comment by johnhtodd** [comment]
Gelin: I understand the distinction you're making, but I'd still argue that this sounds like something that should go into dnsdist, since dnsdist seems to be more flexible and very focused on how to manage forwarders already under various circumstances. You already would sort of get this if you put dnsdist in front of your recursive resolvers. After a certain number of failures, or speed decrease, you would get automatic shifting between forwarders.  Your recursive resolver would just be another forwarding destination in the list with a higher preference, even if it, too, had forwarders.

**Comment by gelin** [comment]
@johnhtodd Yes! I've come to the same idea. Thank you.

**Comment by mnordhoff** [comment]
The downside is that you lose local DNSSEC validation if dnsdist is forwarding to a remote resolver.

Maybe using DoH/DoT would make that less problematic.

**Comment by gelin** [comment]
@johnhtodd Sorry, I want to continue this off-topic discussion a bit.

Dnsdist is able to choose a backend server based on its current availability based on health checks (or some statistics based on previous answers from the server in case of "lazy" checks). The availability or unavailability is a global server state.
However, I want to resend the query to another server (or server pool) if the answer is servfail. And this decision must be performed per each query, regardless the current state of the backends. However, in dnsdist there is no response action to resend the query, it can only drop or delay the answer.

So, I still don't have an idea how to forward DNS query to another backend server if the main resolution completed with servfail, so the client doesn't see servfail at all...

**Comment by johnhtodd** [comment]
@gelin Yes, we've been hoping for the same thing for years but the development team at PowerDNS has pretty clearly said that it will never happen. There is clearly a need for it in many circumstances, so I suppose we need to continue the concepts of "hacks" to make this work. One way I can see this result is to look at the DNSTAP output of dnsdist and search for SERVFAIL results. The "sidecar" program that looks at the output then would feed those domains into a different listening port on localhost, which was then in turn tied to a different server pool but which used the same cache as the main pool.  Entries would (slowly) be inserted into the cache if they were successfully answered by the different resolver pool, but the problem is that the clients would have _already_ received a SERVFAIL from dnsdist, meaning they would not retry. Subsequent requests for the same qname/qtype would get a result for as long as the dnsdist cache item was valid. This is ugly, but possible, and would partly solve the problem for some queries but not the first queries.  Your original query (use forwarders first, then use authoritatives) would be answered by this method in cooperation with dnsdist, and I still think that dnsdist is the only & best place for this type of logic to exist.

Ideally, dnsdist could "split" a query while it was still in flight, perhaps after a certain number of milliseconds without a valid answer, OR at a SERVFAIL or REFUSED result no matter how fast/slow.  That split query would go to a specify-able pool, which would possibly have different pathing and potentially valid answer, which would then "pop" the first query if a result came back (or at least before sending a SERVFAIL/REFUSED the first query path would check the cache again to see if any new answers appeared before replying to the client.) I am not an expert in the internals of dnsdist, but this doesn't seem to be massively difficult, which means it is probably massively difficult.  :-)  It does increase complexity, which I know is not desirable, but there are things on the internet that just can't be fixed (no matter how much we wish they would be) that this method would solve. These aren't protocol failures or bad auth server issues - these are networking failures or policy issues that need another solution method to provide more robust resolution.

**Comment by rgacogne** [comment]
Re-opening since #12388 is only for dnsdist.
