### ISSUE TITLE
dnsdist: Be consistent about "ruleRefused", "ruleNXDomain" and "ruleServFail" counters

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#11498]
- Program: dnsdist 
 - Issue type: Bug report

### Short description
Setting a response code via `RCodeAction` does not increase these counters and should. We might also want to check whether we correctly update the `ruleTruncated` one.

**Comment by aj-gh** [comment]
As discussed this causes the metrics for `rule-nxdomain` / `rule-refused` / `rule-servfail` to be off as they don't count these replies.
(Just mentioning so this is found when searching issues on the exact metric names)

This seems to be handled via `DNSAction::Action::HeaderModify` instead of, for example, `DNSAction::Action::Refused` where this would be counted.
At least `self-answered` is correct :wink:
