### ISSUE TITLE
dnsdist: Cache doesn't store records beyond a certain size

### ISSUE THREAD

**Issue by Vascko** [PowerDNS/pdns#11563]
Hi Folks,

 - Program: dnsdist
 - Issue type: Bug report

### Short description
I'm using a dnsdist pool with a cache and it appears that for records beyond a certain size, the cache doesn't commit the result. And there is no error message nor have I found a limitation in the docs that would explain this limit/behavior.
In this case I'm working with SRV records of varying sizes. An example record that makes it to the cache successfully is 590 bytes long and a record that fails to make it into the cache is 35982 bytes long.
It does not matter if I let the client fail from truncated UDP to TCP by itself or if I force TCP from the get go - same result.

### Environment
 - Operating system: RHEL 7
 - Software version: 1.7.0
 - Software source: PowerDNS repository

### Steps to reproduce
Simple pool configuration with a cache:
```
newPacketCache(100000, {numberOfShards=20, maxTTL=86400, minTTL=60, temporaryFailureTTL=60, staleTTL=60, maxNegativeTTL=300, keepStaleData=true, dontAge=false})
setStaleCacheEntriesTTL(3600)
```
Query SRV records with increasing size and observe cache dump and hit ratio.

### Expected behaviour
All records are committed to the cache

### Actual behaviour
Only records up to a certain size make it into the cache

### Other information
I don't have an adhoc way to simulate granular record sizes right now to provide more data but could set that up if there is not an obvious answer/solution to the problem I described.

**Comment by rgacogne** [comment]
It's a design choice, the packet cache will not cache packets bigger than 4096 bytes: https://github.com/PowerDNS/pdns/blob/ca171679ced245e7001aa42a6f3cfc5e5f4f30be/pdns/dnsdist.hh#L1120
I agree it should be properly documented, though!

**Comment by Vascko** [comment]
Thank you, @rgacogne! That makes a lot of sense.

Is there some context behind that design choice? Memory growth limitations? What are the chances that this might become a configurable variable in the future?

**Comment by rgacogne** [comment]
> Is there some context behind that design choice? Memory growth limitations?

Yes! Since we limit the number of entries instead of the exact memory used by the cache (which would be costly to compute accurately), having a cap on the maximum size of entries makes it possible to predict the maximum amount of memory that will be used. It also has the nice benefit that after a while the probability of having to re-allocate when replacing an entry is very low, keeping both memory allocations and memory fragmentation at a low-level.

> What are the chances that this might become a configurable variable in the future?

Very high if someone cares enough to write a pull request for it ;-) We would have to turn that constant into a variable, write the Lua binding to make it configurable, the documentation, but also carefully check where that value is used. I see it's used to determine the maximum size of the UDP buffers, where we could likely replace that by a different constant hard-coded to 4096, but also to determine the memory initially reserved for TCP buffers, and for that last one we might have to think twice about what we actually want to do.

**Comment by rgacogne** [comment]
Understood :) I'll mark this as a feature request then. We might be able to squeeze that in 1.8.0 but I cannot really make any promise at this point.

**Comment by Vascko** [comment]
@rgacogne Thank you so much for implementing this! I see this is part of 1.9.0-alpha4. I'll give this a try as soon as I can!
