### ISSUE TITLE
Recursor zoneToCache() fails to load a zone with ZONEMD RR in generic format

### ISSUE THREAD

**Issue by wessels** [PowerDNS/pdns#11724]
- Program: Recursor
 - Issue type: Bug report

### Short description
I am testing the new ZONEMD support in Zone to Cache.  When presented with a ZONEMD record in RFC 3597 generic / unknown RR format, there is an error while loading the zone.  For example:
```
Jun 24 13:19:45 msg="Unable to load zone into cache, will retry" subsystem="ztc" level=0 ts="1656101985.046" exception="Parsing record content (try 'pdnsutil check-zone'): expected digits at position 0 in '\\# 54 7886387a010173ad1c08446717406eaebd277eb6907f00bce681fde58733da02901f38cbc1926b91840ee73290018d25745455b8f3f8'" refresh="60" zone="."
```

### Environment

 - Operating system: Ubuntu 20.04.4 LTS
 - Software version: 4.7.0
 - Software source: compiled from download tarball

### Steps to reproduce

1. configure recursor.conf with lua-config-file option
2. configure zoneToCache() in lua config file
3. zone file has ZONEMD RR in generic format

### Expected behaviour
ZONEMD record in generic format should be parsed successfully, as happens for native ZONEMD format

### Actual behaviour
zone failed to load

**Comment by mnordhoff** [comment]
FWIW, I haven't checke,d but this is probably because of #804.

**Comment by Habbie** [comment]
> FWIW, I haven't checke,d but this is probably because of #804

Very likely.

**Comment by wessels** [comment]
Also I should perhaps mention that as we are planning to add ZONEMD to the root zone, we are debating between native or generic format when publishing the zone to internic.net servers.  IMO it would be preferable that this bug did not factor into that decision.

**Comment by mnordhoff** [comment]
I'm sure it would be troublesome, but maybe publishing both would be best?

FWIW, Auth has an [`upgrade-unknown-types`](https://doc.powerdns.com/authoritative/settings.html#upgrade-unknown-types) setting (added in #9623). It would probably make sense to port equivalent functionality to Recursor.

On the one hand, Zone to Cache avoids most of the performance implications, since the root zone is relatively small and infrequently updated, and parsing a zone file is more straightforward than querying a database. On the other hand, someone is inevitably going to want to use ZTC on a large TLD.

**Comment by omoerbeek** [comment]
I'll investigate this week how much work it would be to either use the code from #9623 or provide a custom solution specifically for ZONEMD records.
