### ISSUE TITLE
2023-11-27: new addresses for b.root-servers.net

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#12897]
https://lists.dns-oarc.net/pipermail/dns-operations/2023-May/022044.html

**Comment by omoerbeek** [comment]
A note to anybody reading this: there is no reason rush to update your root-hints *now* (or the default root hints built into the Recursor), because:
1. The change will only go live November 23, 2023. The new addresses *might* respond today, but tomorrow can be different.
2. The root hints refresh mechanism in the Recursor will work as long as at least one of the addresses in the hints produces a result to a `. NS` query. Currently there are 13 v4 and 13 v6 addresses, and only two of those will change.
