### ISSUE TITLE
Prometheus metric labels on custom metrics

### ISSUE THREAD

**Issue by johnhtodd** [PowerDNS/pdns#13359]
- Program: dnsdist
 - Issue type: Feature request

### Short description
The ability to add labels to custom metrics would be extremely sane

### Usecase
When custom metrics are used, it would be very useful to have labels as an option to include in the fully-formed Prometheus metric/label set.  Currently, only metric names can be unique, which forces very fragile and awkward parsing by the person performing reports. Having metric labels would match Prometheus standards for naming and make life easier for summarizations and searching on the PromQL side of things.

### Description
Custom Prometheus style metrics are amazingly useful, but often require extensive re-writing to make them comply with sane methods of labeling. Putting all the data into the metric name causes a lot of work either on the parsing side of the tool, or on the actual database queries to compile multiple metric names into a single report. I won't bore you with the details of how horrible wildcards or regexps are inside of metric names, but I assure you it is awful.

If I have several data points that I want to create metrics for, then I have to create each metric individually, and the only thing I ca do is put cardinality-incremental data into the metric name itself. The current method that dnsdist permits custom metrics allows only this style of metric definition as far as I can see (I show the output below from a hypothetical metric scrape):
```
dnsdist_custom_block_counter_192_168_10_10 55
dnsdist_custom_block_counter_192_168_10_11 993
(etc.)
```
This will cause queries in Prometheus to be really, really ugly with wildcards in the metric name.  Metric names shouldn't contain highly change-able data, but I'm seeing no way to avoid doing that in order to store what should be labels in the Prometheus data somehow.

According to https://prometheus.io/docs/practices/naming/ a preferred method would be to use labels, so queries would be much easier and less awkward. I agree, having lost many hours of my life to trying to make wildcards work in metric names (hint: it's not pretty, easy, or even really useful.)

A better way:
```
dnsdist_custom_block_counter{ipv4address="192.168.10.10"} 55
dnsdist_custom_block_counter{ipv4address="192.168.10.11"} 993
```
This would also then allow for variable-based labels that didn't have to be declared with "declareMetric" for each possible unique label set - this would be WAY more flexible for storing lots of data about specific items that are to be counted. Having mulitple labels would be even more fantastic.

This would mean some changes in the functions that are used after a metric is declared.  In the lines below, I show the old method, and a potential new method on the same line:
```
incMetric(name[, step])   ->   incMetric(name[, step][, label][, label...])
decMetric(name[, step])   ->   decMetric(name[, step][, label][, label...])
getMetric(name)   ->   getMetric(name[, label][, label...])
setMetric(name, value)   ->   setMetric(name, value[, label][, label...])
```
So in my example, this would possibly be the Lua to create one of the full metrics that I show above:

```
incMetric(custom_block_counter, 1, 'ipv4address="192.168.10.10"')
```

**Comment by johnhtodd** [comment]
Spent a lot of time yesterday hitting my head on the lack of this ability yesterday. We may try to make this a patch in the next few months.  Any suggestions as to methodology before someone starts puzzling over it?

**Comment by rgacogne** [comment]
At a quick glance:
- forget what I said earlier about having to take a lock, either I was mistaken or it changed in the meantime but we already take a read-lock anyway. We would need to take a write-lock when a new combination of labels shows up for a given metric but this is fine.
- we can change the structure of our custom metrics so that we can have several entries for a single metric name, depending on the labels. Something like a `std::map<MetricName, std::map<CombinationOfLabels, MutableCounter, std::less<>>>`, for example. 
- we need to decide how we create the `CombinationOfLabels` key but I guess concatenating the labels with a `,` between them might work well enough
- I wonder if it makes sense to try to convert metrics with a non-empty CombinationOfLabels value to carbon? Probably not.

**Comment by johnhtodd** [comment]
> * we need to decide how we create the `CombinationOfLabels` key but I guess concatenating the labels with a `,` between them might work well enough

I think this would just be sorting all the labels to determine if a label set is unique, because it may be the case that an implementer doesn't do the label names in all the same order every time.  It does seem to be the case that every set of labels is a unique key, though.

> * I wonder if it makes sense to try to convert metrics with a non-empty CombinationOfLabels value to carbon? Probably not.

I think not.  The implementer will decide if they use labels or not, and they will take a different path to managing metrics if they are using carbon.  They just won't use labels in their config.  So... not sure if that's worth the effort because it will be a feature that probably isn't ever used because of the nature of the different monitoring environments.

**Comment by johnhtodd** [comment]
Also: there is some work that is going to be done on this shortly here, so if there's activity or thoughts on it please post in this thread so we don't miss anything important during the "quiet thinking" phase.

**Comment by esensar** [comment]
I have prepared a draft PR for this, just to check if I am going in the right direction (#14956). I haven't done anything for carbon. If labels are used, that will cause duplicate metrics for carbon in the current implementation. We could change it to only consider metrics that don't have any labels or we could do some weird metric name generation from labels, which I am not sure is a good idea.

I also think I haven't generated the `CombinationOfLabels` key correctly, because as @johnhtodd mentioned, we don't want to have a requirement that all labels are put in the same order everywhere. That should be a simple change though.
