### ISSUE TITLE
When the recursor is configured to use the TCP protocol for outbound query, TCP fd leakage problem will occur

### ISSUE THREAD

**Issue by zjs604381586** [PowerDNS/pdns#13422]
- [x] This is not a support question, I have read [about opensource](https://www.powerdns.com/opensource.html) and will send support questions to the IRC channel, [Github Discussions](https://github.com/PowerDNS/pdns/discussions/) or the mailing list.
- [x] I have read and understood the ['out in the open' support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/)

 - Program: Recursor 
 - Issue type: Bug report

### Short description

When the recursor is configured to use the pure **TCP** protocol for outbound parsing, after one parsing is completed, the TCP connection will be placed in the **TCPOutConnectionManager**. When the back-end authority closes the TCP connection, after a period of time more than 10s(`tcp-out-max-idle-ms=10000`), the **houseKeeping** scheduling thread executes the The connection cleaning function in TCPOutConnectionManager, with `TCPOutConnectionManager::cleanup()` method, but the smart pointer of **Connection.d_handler is not released at this time because its reference count is 2**. At this time, check the fd status on the machine, and the recursor will have a **CLOSE-WAIT** status.
![image](https://github.com/PowerDNS/pdns/assets/17305630/19c0ddb2-560c-48bc-94dd-0021523ae20c)

#### My troubleshooting：
According to my troubleshooting, the reference count of **Connection.d_handler** is increased to **2** after the first TCP read in the **tcpsendrecv() function** in the **lwres.cc file**, code is `ret = arecvtcp(packet, 2, connection.d_handler, false) `; Causes the connection to not be closed during **cleanup()**. When requesting parsing out of the network again, the last **connection.d_handler** smart pointer will be released, and the fd in the **CLOSE_WAIT** state will also be closed. It feels like the Key is cached in **MTasker. Is this d_eventkey Member variables**?

### Environment

 - Operating system: debian 10
 - Software version: rec 4.8.x
 - Software source: 

### Steps to reproduce

1.  Force recursor to use pure TCP protocol when querying authority when going out of the network
2. 
3. 

### Expected behaviour

TCP fd can be closed normally, there is no fd in **CLOSE_WAIT** state
### Actual behaviour

TCP fd failed to close normally, there is fd in **CLOSE_WAIT** state

**Comment by omoerbeek** [comment]
When I did the ougoing DoT code I made sure to verify there where no leaks. It can take a while for an TCP connection to be cleaned, but it will be closed at some point.

Are you actually seeing growing fd counts over a long period of time?

**Comment by omoerbeek** [comment]
I will do some tests soon.

**Comment by omoerbeek** [comment]
Here's wat I observed: 

on a recursor that does nothing after a connection is marked CLOSE_WAIT, it does not get cleaned. The reason is that via `PacketId` and `MTasker` there are cases where a ref too that connection remains. Only when some queries are processed that lead to mthreads being created (so no packet cache hits), `MTasker` will release the ref to that `PacketID`, which results in actual cleanup.

Note that `MTasker` is a thread local object, so the activity has to be by the thread that holds the ref. That thread could be a thread that does not a lot of resolving work, such as the handler thread (aka. web+stat) thread, which only does root hints resolving and the occasional task execution.

Summary: it can take a long while, especially on a mostly idle recursor, but the connection will get cleaned in the end.

For a busy recursor, the situation does not occur

**Comment by zjs604381586** [comment]
Yes, **MTasker** holds a reference to the smart pointer. When the worker thread makes a request, the cleanup is quite timely. If there is no parsing request, fd will be occupied

**Comment by omoerbeek** [comment]
Even though I do not think this is a real problem, I am thinking about triggering `MTasker` in housekeeping, so that on an idle recursor the `CLOSE_WAIT` connections and their corresponding file descriptors are cleaned up more quickly. But it is not an urgent thing.

BTW: _parsing_ is not exactly the right term, _processing_ is better.
