### ISSUE TITLE
pdnssec increment-serial doesn't respect auto serial

### ISSUE THREAD

**Issue by growse** [PowerDNS/pdns#1355]
It seems that calling pdnssec increment-serial rewrites the SOA record in whatever backend you're using to update the serial to current+1. The issues is that if you're using a gpgsql backend, or something that supports autoserial, this resets the serial record from '0' to something else. This causes autoserial to stop working and further updates to domain records now fail to update the serial number.

**Comment by apfohl** [comment]
I discovered another use case. I'm using the new dynamic dns feature in combination with auto serial. But whenever I update a record with `nsupdate` the only possibility to update the serial is `SOA-EDIT`, which does not include a way to use auto serial. It would be nice to have an `SOA-EDIT` mode that manipulates the `change_date` field instead of the `content` field of the `SOA` record.
