### ISSUE TITLE
discussion of ALIAS record support

### ISSUE THREAD

**Issue by glardone** [PowerDNS/pdns#2394]
I had read that it is in implementation support for the CNAME record for domain APEX, named ANAME or ALIAS, to build a record similar to:

@       IN      ALIAS   www.powerdns.com.

http://mailman.powerdns.com/pipermail/pdns-users/2014-September/010892.html
But this feature is implemented in the last version of PowerDNS?
If no, when it will be?
Thank you!

**Comment by pieterlexis** [comment]
Hi @glardone,

This feature is not implemented in any released version of PowerDNS. We're considering releasing a version 3.5 that has this feature (with the warning that it doesn't do DNSSEC correctly on zones with ALIAS). But it could be we push the release of ALIAS into version 4.0.

**Comment by cmouse** [comment]
and it's present in master branch if you want to try it out

**Comment by jasonwilk** [comment]
It's been almost three months since this question has been asked. I'd be very interested to hear the current plan for ALIAS support. Could we get it into 3.5? I've tested what is there and it does _exactly_ what I need. I'd just love to not have to run an unmaintained branch in production.

**Comment by ahupowerdns** [comment]
Jason, it is not going into 3.5 without pressing reasons. It will be in 4.0 though. Please contact me on bert.hubert@powerdns.com to discuss if there are pressing reasons.

**Comment by rektide** [comment]
Can we keep an open ticket for this feature to discuss? I prefer having something central on github to track.

I'm having issues running the branch and master with this feature. I setup a bind backend with a simple zone, but resolved records are not coming back. I've tried to crank up what logging options I can find but all I can see in the powerdns log is `Remote 127.0.0.1 wants 'google.yoyodyne.net.|A', do = 0, bufsize = 1680: packetcache MISS`

I [made a gist](https://gist.github.com/rektide/f1c23ad9393dc40575ce) with the sample zone file & attempt to dig the record. I'd like to see this ticket reopened and used to discuss the feature until it is released, but if I should take another approach please let me know. Really looking forward to seeing this in action.

**Comment by Habbie** [comment]
Reopened for discussion!

**Comment by Habbie** [comment]
@rektide do you have recursor= set in pdns.conf? If not, can you try that?

**Comment by jasonwilk** [comment]
I have it working in dev. I'd just prefer not to have to run a feature branch in production!

**Comment by rektide** [comment]
Working for me, now! I set `recursor = w.x.y.z` and it's better now. Running master. Sweet!

Habbie mentioned in chat, as an alternative to directly using master,  
> like, [71a7acf1288b65b972160d895e7f958679f3b686](https://github.com/PowerDNS/pdns/commit/71a7acf1288b65b972160d895e7f958679f3b686) is quite a stable snapshot i think

**Comment by jasonwilk** [comment]
It's been a little over a year since the ALIAS branch was created. Any updates on when we will see it or what the plans are?

**Comment by Habbie** [comment]
As said, it is on the master branch, which means it will be in 4.0.0. You should expect a release from master around December - we are moving things around and building a lot of new features.

What we still need is feedback on the functionality itself - do you have any for us?

**Comment by jasonwilk** [comment]
It was requested earlier in this thread that I email Bert directly (which I did). It does exactly what we need it to do.

**Comment by nickmarden** [comment]
@pieterlexis, I tried out the 4.0.0-alpha2 branch and ALIAS works mostly as I expected. However, it seems that A or AAAA records synthesized by the ALIAS mechanism are not signed by the available keys in a DNSSEC-enabled zone.

Your comment at the beginning of the thread:

> We're considering releasing a version 3.5 that has this feature (with the warning that it doesn't do DNSSEC correctly on zones with ALIAS). But it could be we push the release of ALIAS into version 4.0.

seems somewhat ambiguous whether (a) the lack of DNSSEC support for ALIAS was expected to be a problem only if ALIAS made it quickly into 3.5, or (b) it was never expected that ALIAS + DNSSEC would work together, even in 4.x.

Unfortunately the absence of dynamic signing on ALIAS records is a deal-breaker for me on using PowerDNS for a cool, high-profile project. So that's why I'm asking.

I can imagine a lot of arguments for and against dynamic signing of the synthesized records in various cases, but since the ALIAS record _appears_ to be an A (or AAAA) record from the point of view of the DNS client - meaning that I am choosing to present the synthesized record to other users as a Very True Fact - shouldn't I (as the authoritative nameserver operator) at least have the option to sign it before I serve it?

Or am I misunderstanding something fundamental here?

Lastly, if this is the wrong place for this question, please direct me to a better place.

**Comment by Habbie** [comment]
Hello,

this is a fine place for the question except we tend to forget about comments on closed tickets. I recommend just copy/pasting your text into the body of a new ticket, and we can discuss there!
