### ISSUE TITLE
deterministic ECDSA?

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#2720]
http://tools.ietf.org/html/rfc6979 - should we be using this in our ECDSA signers (botan, polar) to increase performance?

(Suggested by @fanf2 on ldns-users)

**Comment by Habbie** [comment]
@rgacogne reports our mbed ECDSA signer uses deterministic signatures

**Comment by rgacogne** [comment]
I think we should use deterministic ECDSA whenever possible, mostly because it prevents screw-up in case of PRNG failure, as the hashed message and the key are taken into account to generate k, instead of resting only on the PRNG.

The current situation is:
* the mbedtls signer uses RFC 6979 deterministic signatures
* the botan signer does not, RFC 6979 support had been added in 1.11.10 and we currently use 1.10.x
* the cryptopp signer does not use deterministic signatures, but it does seem to mix the hashed message with the result of the PRNG to produce k, so it should be safe against PRNG failure

**Comment by Habbie** [comment]
@mind04 @rgacogne any idea about OpenSSL?

**Comment by rgacogne** [comment]
Deterministic (EC)DSA signature is coming with OpenSSL 1.1.0, so be patient.. Good news is, it will be the default without having to change anything.

**Comment by Habbie** [comment]
Awesome! Maybe we should move this information into the docs.

**Comment by stirnim** [comment]
ECDSA support in OpenSSL 1.1.0 has not added deterministic signatures. See also: https://github.com/golang/go/issues/9452

**Comment by rgacogne** [comment]
@stirnim You are technically correct, the (EC)DSA implementation in OpenSSL 1.1.x does not respect RFC 6979. It does, however, use a hash of the private key and the message to be signed to generate `k`, no longer relying only on the output of the PRNG, which was a recipe for failure. agl decided to keep the output of the PRNG in the mix, which means the result is not deterministic, but the key point here is that we are not SOL in case of PRNG failure anymore. See [1] or [2] for the actual code (respectively DSA and ECDSA).

[1]: https://github.com/openssl/openssl/blob/master/crypto/dsa/dsa_ossl.c#L163
[2]: https://github.com/openssl/openssl/blob/master/crypto/ec/ecdsa_ossl.c#L84

**Comment by stirnim** [comment]
@rgacogne Of course, you are correct. However, should the documentation not make this clear? I find the wording "deterministic signatures" in this context misleading. Users which have dual signers and compare the results will still get two different signatures (in contrast if they use RSA or EdDSA).

**Comment by rgacogne** [comment]
You are right, I just opened #3996 to fix that since I should have been more thorough in the first place.
