### ISSUE TITLE
Oracle backend connection

### ISSUE THREAD

**Issue by bias** [PowerDNS/pdns#2831]
I have PDNS 3.4.6 setup to connect to oracle XE, compiled with the Oracle instantclient 11.2 libraries and source (I had issues trying to use the 12.2 libraries). PDNS starts and apparently connects to the DB as there aren't any connection errors (which I get if the wrong password is used). However, using the api to put data or queries (both against the API or using dig) for data manually populated in the database results in nothing - no error or info messages logged in the system logs (I have logging set to 9 in the conf), no pdns api log is created. 

What's the next step in determining what's going on here?

**Comment by ahupowerdns** [comment]
Sadly, the next step is asking us for a commercial support agreement. It is very expensive and time consuming for us to support Oracle issues, and we can't extend our free community support to Oracle because of this. 

Please see https://www.powerdns.com/support.html I'm sorry I have no better news on this. 

It may simply be that the API bits of the Oracle backend have not been hooked up, by the way.

**Comment by bias** [comment]
Nonetheless, having zero error messages makes me disconcerted about the viability of any type of resolution moving forward if I engaged commercial support. Is there any (what are the) assurance of the Oracle backend connection issues being resolved if I acquired carrier grade support?

**Comment by ahupowerdns** [comment]
That assurance is 100%, otherwise we wouldn't do it - can you contact us on powerdns.sales@powerdns.com to discuss further?  Thanks!
