### ISSUE TITLE
remote backend throws on empty dnsname 

### ISSUE THREAD

**Issue by mind04** [PowerDNS/pdns#2876]
https://github.com/ahupowerdns/pdns/commit/7da0574835fd26b5b7a59b49de4f85909c8004b5

**Comment by cmouse** [comment]
I would like to discuss whether the API semantics are correct in the first place. Some people might care what zone you want to start transaction on since not everyone uses mysql as their database. Hiding the zone name is silly. 

Also, problem here is that startTransaction does truncate if zone id is set which should be separated on different API call. 

That said, I can "fix" remotebackend to send null on empty DNSName() at startTransaction, but it is papering over the real problem.

**Comment by pieterlexis** [comment]
@cmouse  is this still an issue?

**Comment by cmouse** [comment]
tbf I have no idea, will try to find out next week.

**Comment by pieterlexis** [comment]
closing, this was created during heavy development work. Please reopen when this is still an issue
