### ISSUE TITLE
backend-generic-mypgsql contradicts itself on required field order

### ISSUE THREAD

**Issue by xxiii23** [PowerDNS/pdns#2987]
https://doc.powerdns.com/md/authoritative/backend-generic-mypgsql/

The mysql/postgresql backend document in the "Basic Functionality" section gives a required field order "for the following six fields", shows seven fields, and then the default query strings given later in the document have 8 fields and show a slightly different field order (disabled and name are swapped around) and then an auth field that is not otherwise mentioned.

Which field order is actually correct, and can fields be omitted, or are all 8 required? What happens if auth or disabled (or any other fields) return NULL?

**Comment by cmouse** [comment]
NULLs on AUTH or DISABLED are converted to 0. Omitting fields causes crash before 7c779a31.

**Comment by cmouse** [comment]
And after that commit it causes SQL backend to cycle and your queries fail.

**Comment by Nasser-** [comment]
تم الإرسال من Outlook




On Wed, Dec 2, 2015 at 12:56 PM -0800, "xxiii23" <notifications@github.com> wrote:





https://doc.powerdns.com/md/authoritative/backend-generic-mypgsql/

The mysql/postgresql backend document in the "Basic Functionality" section gives a required field order "for the following six fields", shows seven fields, and then the default query strings given later in the document have 8 fields and show a slightly different field order (disabled and name are swapped around) and then an auth field that is not otherwise mentioned.

Which field order is actually correct, and can fields be omitted, or are all 8 required? What happens if auth or disabled (or any other fields) return NULL?


---
Reply to this email directly or view it on GitHub:
https://github.com/PowerDNS/pdns/issues/2987
