### ISSUE TITLE
sqlite3 slaving broken when db is in /etc and using systemd defaults

### ISSUE THREAD

**Issue by cmouse** [PowerDNS/pdns#3111]
Version: 4.0-alpha1
OS: Debian 8.2

When doing AXFR from remote host, this error is given:
```
Dec 25 02:21:17 cypher pdns[24625]: Unable to AXFR zone 'mythnet.org.' from remote '46.255.18.39' (PDNSException): Database failed to start transaction: Error while retrieving SQLite query results: attempt to write a readonly database
```

Yet, when checking privileges:
```
# namei -mo /etc/powerdns/db/pdns.db
f: /etc/powerdns/db/pdns.db
 drwxr-xr-x root root /
 drwxr-xr-x root root etc
 drwxr-xr-x root root powerdns
 drwxrwxrwx pdns pdns db
 -rwxrwxrwx pdns pdns pdns.db
```

I am not sure if this is user error or code error, the database is clearly read-write, and the directory is read-write too, so it should be possible to write to the database.

**Comment by Habbie** [comment]
SQLite3 slaving is part of our test suite, and it works for me. Please investigate on your end if you can!

**Comment by cmouse** [comment]
This was caused by following systemd unit file:
```
[Unit]
Description=PowerDNS Authoritative Server
Documentation=man:pdns_server(8) man:pdns_control(8)
Wants=network-online.target
After=network-online.target mysqld.service postgresql.service slapd.service

[Service]
Type=forking
ExecStart=/usr/sbin/pdns_server --daemon
Restart=on-failure
StartLimitInterval=0
PrivateTmp=true
PrivateDevices=true
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_SETGID CAP_SETUID
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=true
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6

[Install]
WantedBy=multi-user.target
```

it seems to read-only protect /etc, which is not a bad thing necessarely

**Comment by pieterlexis** [comment]
We should document that the `ProtectSystem=full` means that write access to the filesystem (/usr, /home and /etc) is restricted.

**Comment by mwiora** [comment]
if someone traps on the same issue as he is NOT locating his sqlite3 db below the path /var/lib/powerdns/pdns.db - you have to place the DB here, as otherwise the services won't be able to access the DB with write access... happened to me under debian 10, latest updates with a current build from master branch

**Comment by ahosie** [comment]
Another possible trap - the **directory** that the db resides in (e.g. /var/lib/powerdns) must be writable by the pdns user, or sqlite will bail out with this "attempt to write a readonly database" error.


For whatever reason pdns-server under debian 10.5 deployed with root:root ownership.
Fixed with:

```chown pdns /var/lib/powerdns```
