### ISSUE TITLE
dnsdist - crashed when cache assigned to the pool

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#3396]
Hi,
when trying to set up a cache on 0.0.731g2b0cd25-1pdns.jessie:

`pc = newPacketCache(10000, 86400, 600)`
`getPool(""):setCache(pc)`

dnsdist crashes:
` kernel: dnsdist[32451]: segfault at 7fa763ffffff ip 00007fa7a9226200 sp 00007fa7a2b473e8 error 4 in libc-2.19.so[7fa7a9194000+1a2000]`

Thanks.
A.

**Comment by rgacogne** [comment]
Hi Aleš,
I tried to reproduce this crash, without success so far. I'm guessing it is caused by a race condition between one thread reading the shared pointer to the cache while another one is updating it, but I would like to be sure this is not something else. If I am not mistaken, you were trying to get a core from this crash, did you succeed by any chance?
Thank you for reporting this anyway!

**Comment by rygl** [comment]
Hi Remi, 

I did not have a chance to play with the cache since the
moment I reported this issue. I will try again, maybe today afternoon.


I will come back to you. 

Regards 

Ales 

On Mon, 22 Feb 2016
03:16:33 -0800, Remi Gacogne wrote: 

> Hi Aleš,
> I tried to reproduce
this crash, without success so far. I'm guessing it is caused by a race
condition between one thread reading the shared pointer to the cache
while another one is updating it, but I would like to be sure this is
not something else. If I am not mistaken, you were trying to get a core
from this crash, did you succeed by any chance?
> Thank you for
reporting this anyway! 
> 
> --
> Reply to this email directly or view
it on GitHub [1].
 

Links:
------
[1]
https://github.com/PowerDNS/pdns/issues/3396#issuecomment-187127915
