### ISSUE TITLE
Dynamic signing of synthesized ALIAS records

### ISSUE THREAD

**Issue by nickmarden** [PowerDNS/pdns#3555]
(Copied over from https://github.com/PowerDNS/pdns/issues/2394, which is closed.)

@pieterlexis, I tried out the 4.0.0-alpha2 branch and ALIAS works mostly as I expected. However, it seems that A or AAAA records synthesized by the ALIAS mechanism are not signed by the available keys in a DNSSEC-enabled zone.

Your comment at the beginning of the https://github.com/PowerDNS/pdns/issues/2394 thread:

> We're considering releasing a version 3.5 that has this feature (with the warning that it doesn't do DNSSEC correctly on zones with ALIAS). But it could be we push the release of ALIAS into version 4.0.

seems somewhat ambiguous whether (a) the lack of DNSSEC support for ALIAS was expected to be a problem only if ALIAS made it quickly into 3.5, or (b) it was never expected that ALIAS + DNSSEC would work together, even in 4.x.

Unfortunately the absence of dynamic signing on ALIAS records is a deal-breaker for me on using PowerDNS for a cool, high-profile project. So that's why I'm asking.

I can imagine a lot of arguments for and against dynamic signing of the synthesized records in various cases, but since the ALIAS record _appears_ to be an A (or AAAA) record from the point of view of the DNS client - meaning that I am choosing to present the synthesized record to other users as a Very True Fact - shouldn't I (as the authoritative nameserver operator) at least have the option to sign it before I serve it?

Or am I misunderstanding something fundamental here?

**Comment by Habbie** [comment]
Hi Nick,

thank you for your extensive question. The honest answer is that simply no work has been done on making it work with DNSSEC yet. We want this to just work (but we haven't looked at how hard it would be). We do not worry about the 'authority' argument :)

That said, we'd love to know about your high-profile project. Want to drop me a line at peter.van.dijk@powerdns.com to discuss? We'd love to help out, as explained in http://blog.powerdns.com/2014/05/05/how-to-talk-to-an-open-source-software-project-as-a-large-scale-or-otherwise-interesting-user/

Peter

**Comment by Habbie** [comment]
Our 'work in progress' docs on ALIAS also mention we need to sign: https://github.com/PowerDNS/pdns/blob/master/docs/WIP/alias.md#dnssec-processing

**Comment by nickmarden** [comment]
@Habbie - I'll drop you a private email to discuss our case.

Just FYI: the mention about DNSSEC in the ALIAS doc (https://github.com/PowerDNS/pdns/blob/master/docs/WIP/alias.md#dnssec-processing) was a bit unclear to me because the document was written somewhat like an RFC ("the implementation should do X") rather than a document about how PowerDNS in particular would handle the implementation. Because of this I wasn't clear on whether PowerDNS did or didn't handle the situation mentioned there:

> If the zone is signed with DNSSEC, the synthesized records will need to be signed too, since answers would otherwise be rejected as BOGUS.

That can be interpreted in one of two ways: "we are aware of this need and therefore we will of course sign the ALIAS records dynamically in the PowerDNS implementation of ALIAS", or "our current implementation doesn't handle this situation so we understand it to be lacking w.r.t DNSSEC at present". I was hoping for the former, but (for now) it's the latter.

At any rate, PowerDNS is clearly brilliant and I hope that this one issue can be resolved to make it even more brilliant for people with my use case :-)

**Comment by Habbie** [comment]
That's the WIP (Work In Progress) part, sometimes all that is registered are thoughts instead of coherent descriptions of present implementation :)

**Comment by Habbie** [comment]
Can confirm that I am also not seeing signatures right now :)

**Comment by Habbie** [comment]
The current hurdle in signing the responses is that the code that takes data from backends and signs it (`PacketHandler::questionOrRecurse`), when it sees an ALIAS, it hands the packet off to the DNS Proxy (dnsproxy.cc) that does the recursive lookup, fills in the results, and sends the packet out. This is done this way so that the (database-connected!) PacketHandler thread can go on to do other things while DNS Proxy waits for the recursive answer. The DNS Proxy, of course, has no idea about signatures or keys etc. So this is all a bit hairy.

**Comment by Habbie** [comment]
Our SOA being wrong on NODATA responses from the backend recursor has similar reasons.

**Comment by Habbie** [comment]
After #3733 is merged we will do signing of ALIAS on outgoing AXFR, which makes the original reporter mostly happy. Leaving this open for real dynamic signing.

**Comment by Habbie** [comment]
Correction, added dynamic signing as a bullet point to #3838 so closing this one.

**Comment by bAndie91** [comment]
hi @nickmarden  and @Habbie , I faced a similar need: to have both "pointer"-like records (but not CNAME) and sign them too.
so i sketched a dirty patch to have LUA records directly reflect an other record of the zone and let LUA records expanded on AXFR.
see https://github.com/bAndie91/pdns/commit/2c6bd32113dbfcc3d0dc24ffd1b7a8d9f1fc2abb
i hope it helps.

**Comment by Habbie** [comment]
Hi! This is a comment on a closed ticket, which means we will never again remember to look at it. Do you want to file a pull request with your patch instead? Thanks!
