### ISSUE TITLE
addQPSLimit and addPoolRule order issue

### ISSUE THREAD

**Issue by rygl** [PowerDNS/pdns#3638]
Hello,

I have this issue. I have a list of bad hosts like this:

`BadHosts = makeRule({
"46.13.3.246",
"46.13.4.194",
"46.13.5.42",
"46.13.8.74",
"46.13.8.250",
"46.13.11.157",
"46.13.12.130",
...
})`

Then I want to set a qps limit per each IP on the list and send all of them to quarantine pool:

`addQPSLimit(BadHosts, 1)`
`addPoolRule(BadHosts, "quarantine")`

The issue is that in this case the pool rule does not work: nothing goes to quarantine pool (the qps limit works)

`> showServers()`

`#   Name                 Address                       State     Qps    Qlim Ord Wt    Queries   Drops Drate   Lat Outstanding Pools`
`0   beluga1              93.153.117.2:53                  up  2862.9       0   1 100     310663    4491 257.1  11.7         187`
`1   beluga2              93.153.117.3:53                  up  2729.6       0   1 100     311013    4757 290.9   6.4         171`
`2   beluga3              93.153.117.4:53                  up  2867.2       0   1 100     309958    4174 183.7  11.8         186`
`3   beluga4              93.153.117.5:53                  up     0.0       0   1 100          0       0   0.0   0.0           0 quarantine`
`4   murena4              93.153.117.37:53                 up     0.0       0   1 100          0       0   0.0   0.0           0 quarantine`

If the order of qps and pool rule is reversed pool rule works, qps rule matches the traffic (which is strange because rules processing should stop here) and the qps limit does not work.

Ales

**Comment by rgacogne** [comment]
There are two separate issues here:
* you are sharing the same `DNSRule` between two rules, and therefore the counters are not behaving like you would expect them to
* the `QPSAction`, used by `addQPSLimit()`, returns Allow and not None when the threshold is not reached, effectively preventing the next rules from being processed

For the first issue, you need to understand that since you are using the same rule object twice, what you see in `showRules()` is the same counter twice. You probably want to do something like this instead:
```
BadHosts = { "46.13.3.246", "46.13.4.194", "46.13.5.42", "46.13.8.74", "46.13.8.250", "46.13.11.157", "46.13.12.130", ... }
addQPSLimit(makeRule(BadHosts), 1)
addPoolRule(makeRule(BadHosts), "quarantine")
```

For the second one, this should be fixed by #3641.
