### ISSUE TITLE
dnsdist: Answer returned by SpoofCNAMEAction not resolvable by some stub resolvers

### ISSUE THREAD

**Issue by janeczku** [PowerDNS/pdns#3679]
`SpoofCNAMEAction` currently does not resolve (follow) the CNAME. Some stub resolvers can't handle a CNAME only response. Would be nice if functionality similar to the `followCNAMERecords` function in the PowerDNS Recursor Lua API could be added.

**Comment by rgacogne** [comment]
Something similar to `followCNAMERecords` is quite unlikely IMHO, because `dnsdist` is not a resolver and wouldn't know how to get the records. We could add an option to `SpoofCNAMEAction()` to add additional, static, A or AAAA records in the response, but then you would probably be better off using `SpoofAction()` directly.

**Comment by ahupowerdns** [comment]
@janeczku which resolvers can't follow a CNAME? Just curious if you've seen this behaviour.

**Comment by janeczku** [comment]
@ahupowerdns I have only seen this in on Android using C libcurl library. It's probably an edge issue. There is a hint in RFC2317 that this might have been more widespread issue - at least 18 years ago 😄 :

> Some older versions of name server software will make no effort to
>    find and return the pointed-to name in CNAME records if the pointed-
>    to name is not already known locally as cached or as authoritative
>    data.  This can cause some confusion in resolvers, as only the CNAME
>    record will be returned in the response.

@rgacogne Makes perfect sense. Closing this issue and rather try to fix my Android app!
