### ISSUE TITLE
PowerDNS crashing - MariaDB read-only mode

### ISSUE THREAD

**Issue by foxxlpaul** [PowerDNS/pdns#3793]
**Problem:**
PowerDNS runs fine but when there are unfresh domains, the slaves keep crashing and restarting until the master has finished refreshing.
On the slaves MariaDB is used in read-only mode because of master/slave operation.

`Exiting because communicator thread died with error: GSQLBackend unable to refresh domain_id 4655: Failed to execute mysql_query, perhaps connection died? Err=1: The MariaDB server is running with the --read-only option so it cannot execute this statement`

**SOFTWARE:**
Centos 7.2.1511
PowerDNS 3.4.8 from repo: https://www.monshouwer.eu/download/3rd_party/pdns/el7/x86_64/ 
Backend: MariaDB 5.5.47

**CONFIGURATION:**
PowerDNS used as supermaster
MariaDB master - slave setup (with slaves in read-only modes)

MariaDB slaves my.cnf:
[mysqld]
read-only=1

How can we tell PowerDNS that it is on a read-only slave?

**Comment by pieterlexis** [comment]
Hi @foxxlpaul,

Am I correct in assuming that you do not (intend to) use AXFR, but merely rely on database replication? If so, the `slave` setting on your slaves should be `no`, as this enables SOA freshness checking and AXFR initiation. Your slaves will still get the updates to the zones because of the database slaving the data.

Best regards,

Pieter

**Comment by foxxlpaul** [comment]
Great thanks Pieter, that makes sense!
