### ISSUE TITLE
pdnsutil edit-zone should offer to increase the serial

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#3814]
Right now `edit-zone` does not automatically touch the SOA. Suggestion: if edits are made but SOA is untouched, maybe we can do one of these things:
1. warn about it
2. offer to fix it
3. respect soa-edit settings

**Comment by zeha** [comment]
Related: API has lots of lines to do the SOA-EDIT stuff, and it feels like they are way too many. There's no specific area to work on, except cutting down the number of lines.

**Comment by Habbie** [comment]
2136 also uses SOA-EDIT, and of course SOA queries and the mastercommunicator (for NOTIFY), etc. Some refactoring/centralisation might be in order.

**Comment by tinuzz** [comment]
In the context of this issue, I was trying to write a shell script that:

1. invokes pdns-util edit zone 
2. checks the output for a line that says 'No changes to apply.
1. invoke pdns-util increase-serial if no such line is found

However, step 2 is hard to do, because the message is printed to stdout, rather than stderr, and I haven't found a way to capture stdout without causing at least _some_ issues with the editor.

My request would be that this particular message be sent to stderr instead of stdout.

https://github.com/PowerDNS/pdns/blob/master/pdns/pdnsutil.cc#L1068

`sed '1068 s/cout/cerr/' pdnsutil.cc`

Best regards,
Martijn.

**Comment by bjoe2k4** [comment]
:+1: would prefer option 3
