### ISSUE TITLE
pandoc confusion in recursor configure

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#3943]
```
checking for pandoc... no
configure: WARNING: pandoc is missing, unable to build manpages.
```

note: WARNING
```
$ make
...
  CXXLD    rec_control
  GEN      pubsuffix.cc
  CXX      pubsuffix.o
  CXXLD    pdns_recursor
echo "You need pandoc to generate the manpages"
You need pandoc to generate the manpages
exit 1
```

note: error. Also note that the binaries have been built, so it's not super painful (and I could always point make at them myself), but the whole situation is a bit confusing. Other files that require tools (bison/flex in auth, ragel) do error on configure. I see the difference - you NEED ragel/bison/flex to build the binaries, you don't need pandoc to build the binaries, but it's been biting me.

**Comment by Habbie** [comment]
And, understandably but annoyingly, installing pandoc does not help until I re-run configure :)

**Comment by pieterlexis** [comment]
right, so this is only an issue when building from git, in the distribution tarballs, the manpage is included. When implementing this, I was asked not to mess fail on configure.. As an ugly workaround, we could create the manpage with `touch` in the makefile, but that could result in a fuckup and us not shipping the manpage (but this is automated, so that shouldn't happen)

**Comment by Habbie** [comment]
Nah, don't paper it over with hacks that might lead to empty manpages. I feel 'deal with it' is a valid response, to be clear :)

**Comment by pieterlexis** [comment]
then deal with it :)
