### ISSUE TITLE
dnsdist : supermaster not working

### ISSUE THREAD

**Issue by Rico29** [PowerDNS/pdns#4039]
Hello,

Supermaster fonctionnality is broken when using dnsdist in front of pdns slave server.
Slave server sees the NOTIFY request come from 127.0.0.1 because of dnsdist proxy, and tries to get the SOA and NS records from the host who sends the notify (127.0.0.1 here).

As the zone is not present on slave, request to 127.0.0.1 can not be replied :

Jun 24 15:52:29 Remote 127.0.0.1 wants 'domain.biz|SOA', do = 0, bufsize = 512: packetcache MISS
Jun 24 15:52:29 Received NOTIFY for domain.biz from 127.0.0.1 for which we are not authoritative
Jun 24 15:52:29 Remote 127.0.0.1 wants 'domain.biz|SOA', do = 0, bufsize = 512: packetcache MISS
Jun 24 15:52:29 Error resolving SOA or NS for domain.biz at: 127.0.0.1: Query to '127.0.0.1' for SOA of 'domain.biz' produced no answers

Regards,
Cédric

**Comment by rgacogne** [comment]
I did absolutely no testing on this, but perhaps something like e230f8afd4fa3e7cbc6143abc743ca0e4537a20c might work.
It makes the auth use EDNS Client Subnet on notify queries received from a trusted notification proxy, if any.

**Comment by spheron1** [comment]
I've just run into this on our authoritative PowerDNS servers behind dnsdist.

Existing DNS zones which have already been created by a NOTIFY from a supermaster (all running BIND/named in my case) before introducing dnsdist are fixed by adding trusted-notification-proxy pointing to the dnsdist server, but creating any new zones seems to still fail:

```
pdns_server[16145]: Jul 19 14:03:57 Received NOTIFY for blah.com from ::1 for which we are not authoritative
pdns_server[16145]: Jul 19 14:03:57 Received NOTIFY for blah.com from ::1 for which we are not authoritative
pdns_server[16145]: Jul 19 14:03:57 Error resolving SOA or NS for blah.com at: ::1: Query to '::1' for SOA of 'blah.com.' produced no answers
pdns_server[16145]: Jul 19 14:03:57 Error resolving SOA or NS for blah.com at: ::1: Query to '::1' for SOA of 'blah.com.' produced no answers
```

I've tried the 4.0.0 release of the PowerDNS authoritative server as well as the latest master branch build from repo.powerdns.com (0.0.1138g41f6e66-1pdns.el7).

I'm using the following to configure the backend PowerDNS server in dnsdist:

`newServer({address="[::1]:5300", useClientSubnet=True})`

As a side note to anyone else who comes across this behaviour, you may want to add rules to dnsdist to filter where you accept notifications and transfer requests from, but the addAction() examples described at http://dnsdist.org/README/#axfr-ixfr-and-notify don't work in dnsdist 1.0 because as far as I can see, they were only added in #3936 which was after the 1.0 release and so you need to use the master trunk build (I'm running 0.0.1120g41f6e66-1pdns.el7 at the moment).
Hopefully that will help someone avoid some of my head scratching!
