### ISSUE TITLE
Large lua scripts break the recursor

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#4225]
I'm looking at scaliability of lua scripts in 4.0.0 on a box with 2gb mem. The following lua script runs fine in the recursor:

`perl -E 'say "t ={"; say qq["$_-foo.com",] for 0 .. $ARGV[0]; say "}"' 100000 > script.lua`

But change that arg to 1000000 (1m) and whilst `lua` commandline program runs it in ~1.5 seconds, recursor never manages to load the script and never starts answering queries and doesn't output anything to the log (just freezes before where the `Loaded 'lua' script from '...'` log lines nomally come). CPU time spikes initially (as normal when loading a lua script) but then pdns just freezes not using any cpu time which seems very strange. There appears to be a similar issue on lua script reload.

The largest it can load on my system appears to be around 530k entries.

I'm not wanting a debate about the merits of shoving a tonne of data into a lua script by the way ;-)

**Comment by rgacogne** [comment]
Would you mind stracing the process? In my tests it always ends up either loading correctly the script if I have enough memory available or getting killed by the OOM-killer otherwise, so my guess would be that your kernel is busy swapping or something like that. Keep in mind that the script is loaded by every recursor thread, so the total memory required to parse it depends on that setting too.

**Comment by Habbie** [comment]
On a sidenote, you may want `newDS` instead of your table. I trust this will not fix your vague issue though :)

**Comment by mzealey** [comment]
I'm unable to reproduce this now (with 4.0.1 although I doubt that's a big change from 4.0.0). I don't think it was OOM I'd hope I would have noticed this, but I'll close as I can't reproduce.
