### ISSUE TITLE
ANY queries to Recursor 4.x return different results from cache and from uncached queries (DNSSEC records)

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#4292]
I see some slightly weird behaviour in 4.0.1 rec

Set udp-truncation-threshold=4000 and run `dig @127.0.0.1 ANY nos-avg.cz`. First time it is 2.2kb second and following it is 1.3kb - this is with packetcache disabled. You can also try querying RRSIG/DNSKEY records to load more records into the response.

**Comment by mzealey** [comment]
This is a regression against rec 3

**Comment by ahupowerdns** [comment]
This is unrelated to truncation. It is related to ANY queries which, when transmitted to resolvers, give surprise results anyhow. It turns out that when running from the cache we stuff in less DNSSEC records than when running from the direct query. 
If we wanted to solve this, ANY should work harder at finding DNSSEC records. But since you still can't count on what ANY will do (it gives you "whatever happens to be in the cache right now"), let's not  make this a priority.

**Comment by omoerbeek** [comment]
I believe this has been fixed.
