### ISSUE TITLE
pdns-recursor on Raspberry Pi using Ubuntu Mate 16.04

### ISSUE THREAD

**Issue by driegel** [PowerDNS/pdns#4352]
Hello, 

I am using Raspberry Pi with Ubuntu Mate 16.04 (armhf)
Would it be possible to have 4.0.1 packets in the repository?

Thank you very much!
Daniel

**Comment by pieterlexis** [comment]
hi @driegel,

At the moment, our raspberry pi builders are inoperative. After these are operational again, we might consider building for Ubuntu on ARM. But I am afraid both won't be soon because of other concerns. I think you're better off grabbing the [Ubuntu 16.10 package source](http://packages.ubuntu.com/source/yakkety/pdns-recursor) and building it yourself.

**Comment by driegel** [comment]
Thank you very much for this info.

I started rebuilding the package but towards the end the g++ compiler
crashes. I need to do further tests to see if this problem is Raspberry
specific or Ubuntu 16.04 specific.

Thanks again!

**Comment by Habbie** [comment]
@driegel please add 2 gigs of swap and try again

**Comment by driegel** [comment]
@Habbie Thanks, even 1 gig of swap helped to compile the package properly.

**Comment by Habbie** [comment]
Closing this, we will have these builds at some point, even without this ticket.
