### ISSUE TITLE
Need some information about queries is showed in "grepq" command.

### ISSUE THREAD

**Issue by devilsmile86** [PowerDNS/pdns#4773]
- Program: dnsdist
 - Issue type: Information

**Short description**
Hi Team,
I have some concern relate to "qrepq" command (or commands are used in Inspecting live traffic). How can "grepq" keep old queries history? I tried to find them in my system and dnsdist Readme but I not found. If I have a big system with a lot of queries, I worried keep too much queries history can make it comsume a lot of disk space. Can you provide me give me some information below?
- How many queries history will be keep ?
- How much disk space is required or used for "Inspecting live traffic" feature?
- Can "qrepq" (or commands are used in Inspecting live traffic) work with a large of queries?

Thanks !!

**Comment by rgacogne** [comment]
Hi,

`dnsdist` uses two in-memory ring buffers of at most 10000 entries each, one for the queries and one for the responses. It doesn't keep whole queries or responses though, only some basic information about them.

> How many queries history will be keep ?

10000

> How much disk space is required or used for "Inspecting live traffic" feature?

None, everything is kept in memory.

> Can "qrepq" (or commands are used in Inspecting live traffic) work with a large of queries?

Yes.

Please use `dnsdist` mailing-list[1] for this kind of questions in the future, since it's not a bug report or a feature request!

[1]: https://mailman.powerdns.com/mailman/listinfo/dnsdist

**Comment by devilsmile86** [comment]
Thank you very much. Sorry for this inconvenience.
