### ISSUE TITLE
Mysql 5.7 and pdnsutil check-all-zones

### ISSUE THREAD

**Issue by stevie-** [PowerDNS/pdns#4973]
- Program: Authoritative 
 - Issue type: Bug report 

### Short description

We implemented in our monitoring to call `pdnsutil check-all-zones` and parse result to see if there are problems. We notice that on our servers with mysql 5.7 we have an error in the `mysql/error.log` each time we call this command. On 5.5 mysql installations we don't see this log entry.
Command shows correct result and ends with return code 0
```
2017-02-03T13:52:04.813918Z 16595 [Note] Aborted connection 16595 to db: 'powerdns' user: 'powerdns' host: 'localhost' (Got an error reading communication packets)
```

### Environment

 - Operating system: Linux dns-0.domain.net 4.4.0-59-generic #80~14.04.1-Ubuntu SMP Fri Jan 6 18:02:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 - Software version: pdns-server 4.0.3-1pdns.trusty, mysql-server 5.7.14-1+deb.sury.org~trusty+0
 - Software source: powerdns-40-auth repo

### Steps to reproduce
1. create an auth setup with mysql backend
2. create a zone with some entrys
3. run pdnsutil check-all-zones

### Expected behaviour

It should not show in /var/log/mysql/error.log `Note` each time we run command

**Comment by Habbie** [comment]
I presume the `Note` is the observed behaviour, not the expected behaviour?

**Comment by mind04** [comment]
https://www.percona.com/blog/2016/05/16/mysql-got-an-error-reading-communication-packet-errors/

**Comment by stevie-** [comment]
Can you reproduce this behaviour?

**Comment by pieterlexis** [comment]
@dveeden mentioned that this error might show up in the log if the TCP connection is terminated without properly shutting down the MySQL connection. And it is possible the verbosity for this error was increased betwee MySQL 5.5 and 5.7.

**Comment by dveeden** [comment]
Yes @pieterlexis is right.

Example:
```c
#include <mysql.h>
#include <stdio.h>

int main()
{
  MYSQL *mysql, *conn;
  mysql = mysql_init(NULL);

  conn = mysql_real_connect(mysql, "127.0.0.1", "msandbox", "msandbox", "test", 5720, NULL, 0);

  if (conn == NULL)
  {
    printf("Uhoh: %s\n", mysql_error(mysql));
  }

  printf("Server version: %lu\n", mysql_get_server_version(mysql));

  mysql_close(mysql);
}
```

If you run this (after changing your connection parameters & compiling with `gcc -Wall -Werror --std=c11 -g $(mysql_config --cflags --libs) mysql_aborted_connection.c -o mysql_aborted_connection`) then this should not create the `Aborted connection` messages.

If you now comment the mysql_close() call then it will print these messages in the error log on 5.7.
This is because in 5.7 [log_error_verbosity](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_log_error_verbosity) is set to 3 by default. Note that this setting is introduced in 5.7 to replace [log_warnings](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_log_warnings) which had its default changed from 1 to 2 in 5.7.

The MySQL Manual has a page with some more details: https://dev.mysql.com/doc/refman/5.7/en/communication-errors.html

Besides not calling `mysql_close()` and a generic network connection issue there is another possible cause of this: hitting a timeout.
