### ISSUE TITLE
dnsdist query counters suffer from integer overflows

### ISSUE THREAD

**Issue by mikedamm** [PowerDNS/pdns#5054]
![image](https://cloud.githubusercontent.com/assets/24718/23110178/1b8e2c94-f6d4-11e6-8fa3-3c479689b779.png)

dnsdist built and running on a 64-bit OS. Query counter for pools and match counter for rules overflow.

**Comment by rgacogne** [comment]
Hi Mike,

Could you please tell us which version you are running? We have fixed similar issues in the past so if you are not running 1.1.0 already, upgrading might help. Would you mind also posting the result of running `showRules()` and `showServers()` via the console, so we know whether the issue is limited to the web interface? Thanks!

**Comment by Habbie** [comment]
Ping

**Comment by tmuncks** [comment]
Same problem in the web-interface here. The counters from showRules() and showServers() are fine though (for my current satte, I'm only seeing the rollover in rules)

> showRules()
#     Matches Rule                                               Action
1   2631607333 (Dst: x.x.x.x/32, y.y.y.y/32) && (Src: x.x.x.x/19, y.y.y.y/19, z.z.z.z/22) to pool secure
2     5727075 All                                                to pool public
![screenshot from 2017-03-22 08-08-05](https://cloud.githubusercontent.com/assets/9822186/24195502/beca6776-0ed8-11e7-847d-6efec2d08a36.png)

**Comment by rgacogne** [comment]
Fixed by #5234.
