### ISSUE TITLE
recursor: Support changing rpzMasters()'s IP dynamically using reload-dns-config

### ISSUE THREAD

**Issue by giganteous** [PowerDNS/pdns#5683]
- Program: Recursor
 - Issue type: Feature request

### Short description
After changing an existing rpzMaster() to a different IP in the dns-config.lua, I noticed the running recursor was retrieving IXFRs from both the old and the new IP.

It would be handy to keep the cache warm and be able to remove or change rpzMasters.

### Usecase
I was trying to change the upstream for an rpzMaster() definition.

### Description
I'd like to update rpzMasters during runtime.

**Comment by rgacogne** [comment]
The "both old and new IP addresses are in use after a `reload-lua-config`" issue should be fixed in master since https://github.com/PowerDNS/pdns/pull/6506, but we are still doing a full `AXFR` after the reload when we could just pick up where the existing thread was (we already have the serial in the zone information).

**Comment by rgacogne** [comment]
> we are still doing a full AXFR after the reload when we could just pick up where the existing thread was (we already have the serial in the zone information).

It's actually more complicated, because some parameters like the default policy, the default or maximum TTL, etc, might have changed, so it's probable safer to reload the zone.

Closing since the real issue, the existing thread not exiting, has been fixed, and I believe the current behaviour is the safest one.
