### ISSUE TITLE
cleanup in /tmp when build-process fails

### ISSUE THREAD

**Issue by klaus3000** [PowerDNS/pdns#5709]
When package building fails, the files in /tmp are not cleaned. Hence, /tmp can run full when building somewhere else. 

IMO it should not build in /tmp but local, or should use always the same build-dir.

```
root@cc-regdev-sbg1:/tmp# du -sch `ls -d */`
156M    tmp.3AoLkwOWyk/
7.1M    tmp.3PfKROUOf6/
7.6M    tmp.4JVbFXhVo4/
7.6M    tmp.6zGpT3J08m/
22M     tmp.daSL6XAoMk/
126M    tmp.dWryJam98F/
1.5G    tmp.kzorfYeiRB/
1.3G    tmp.mxeLLqHKtQ/
892M    tmp.nAxLke9h1c/
600M    tmp.npB3NPXWiU/
9.5M    tmp.p8MBsihiql/
1.1G    tmp.pf03Zpu5y7/
22M     tmp.qWog1UGq5W/
9.5M    tmp.rgHtQQJXRw/
22M     tmp.TRcc7jwN8L/
1.5G    tmp.uNl64tc7G8/
60M     tmp.VmrMgKXTQO/
1.3G    tmp.WXhXs48FeM/
1.3G    tmp.ZRrecAtKgt/
9.8G    total

```

**Comment by zeha** [comment]
Clarification: This is about unsupported stuff in `build-scripts/`, not the autoconf build system.

**Comment by Habbie** [comment]
@klaus3000 as mentioned under Caveats at the bottom of https://github.com/PowerDNS/pdns/blob/master/build-scripts/README.md#caveat, these scripts are provided without support. Furthermore, we don't have these problems because we run them in fresh Docker containers every time.

Patches are welcome if they don't break building for us, but we have no plans to work on this from our side.

Closing ticket, sorry!

(btw, we don't explicitly use /tmp, we leave that to mktemp, so you should be able to override by setting $TMPDIR).
