### ISSUE TITLE
Recursor is not reflecting changes in Auth server records

### ISSUE THREAD

**Issue by mklimkow** [PowerDNS/pdns#6145]
- Program: Authoritative, Recursor, dnsdist 
 - Issue type: Bug report

### Short description

When editing records, changes are replicated to slave BIND server but due to configuration like: https://doc.powerdns.com/authoritative/guides/recursion.html (Scenario 2) are not effective on PDNS server itself. The querries are forwarded to recursor by dnsdist. Then they should be forwarded to auth due to forward-zones-file= statement in recursor.conf. Instead of that recursor answers with cached entry. Only reloading zones on recursor helps. 

### Environment

 - Operating system: Ubuntu 16.04.3 LTS
 - Software version: 4.1.0-1 recursor and auth (also tried on 4.0.8), with mysql backend and dnsdist 1.2.0-1
 - Software source: PowerDNS repository

[recursor.txt](https://github.com/PowerDNS/pdns/files/1606907/recursor.txt)
[pdns.txt](https://github.com/PowerDNS/pdns/files/1606908/pdns.txt)
[dnsdist.txt](https://github.com/PowerDNS/pdns/files/1606909/dnsdist.txt)

**Comment by pieterlexis** [comment]
Is the TTL of these records? The recursor will honor these.

**Comment by mklimkow** [comment]
TTL is 86400. I understand that this might be the expected behaviour of the recursor but on the other PDNS server with almost exact same configuration (but on version 4.0) changes are reflected immediately. So at this point I dont know is this a bug or a feature...

**Comment by pieterlexis** [comment]
This is the correct behaviour for the recursor. If you require fast changes of the record data, lower the TTL of the record or flush the cache for the forwarded domains automatically on a change.

This issue is not a bug or feature request but a support question. Please direct further communication to our [mailinglist](https://www.powerdns.com//mailing-lists.html) or [irc](https://www.powerdns.com/opensource.html). Keeping in mind our [support policy](https://blog.powerdns.com/2016/01/18/open-source-support-out-in-the-open/).
