### ISSUE TITLE
dnsdist: Query Parallelisation/Retry

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdns#6181]
https://mailman.powerdns.com/pipermail/dnsdist/2017-November/000385.html

Some dnsdist deployments would benefit from asking the same incoming question to multiple backends. Think bad network connectivity...

Such "multiplied" outqueries should be able to start after configurable time offsets ("timeouts"), or as an action on a given response (i.e. SERVFAIL). The second part is more like a "retry" mechanism.

**Comment by johnhtodd** [comment]
Other comments on this topic: To bring in some of ahu's comments from the mail thread, there is a desire to implement a "poor man's multi-layer cache" where cache snooping can request an item from multiple [nearby|larger|more performant] caches first without asking them to fetch the object if not in cache. If an answer is obtained, then use that. If no valid answer is obtained (SERVFAIL probably is not "valid") or no answer at all is obtained within a defined timeout, then ask subsequent pools for an answer.  If those subsequent pools do not answer within a defined timeout, proceed to the next pool, etc.  Note: cascading into subsequent pools should not prevent a prior query source from stopping the process if a valid answer is sent in "late".  

Ideally, there would be some indication (tag? variable?) that would indicate from which ruleset the answer was obtained, so it would be possible via external processing based on protobuf tagging to build statistics on pool performance. This might be inherent in the protobuf message when produced, or might be exposed via Lua and could be added with the arbitrary tag functions. This is an incomplete thought though...

**Comment by pavel-odintsov** [comment]
I like this idea. Such aggressive behaviour may be useful when latency is very important.

**Comment by pavel-odintsov** [comment]
Regarding cache snooping idea. I had such plans for my deployment recently. But I postponed this idea because DNS protocol cannot provide information about cache freshness.

To implement it properly, recursive server should provide original TTL and timestamp when record was added into cache. It will provide options to filter our stale data before using it directly.

**Comment by johnhtodd** [comment]
Pavel: I don't understand that comment. The data retrieved from an upstream cache wouldn't be "stale" because as long as the upstream cache (the one being "snooped" on) has a nonzero TTL, that is still valid. My concept of "stale" means that the TTL has expired; that would never be the case. The downstream cache would copy the current TTL from the upstream, which may not be the TTL as provided by the authoritative but is still a non-zero number that indicates non-staleness. This is the same behavior as any forwarder performs. 

Remember that in the model I describe above, the "snoop" action does not mean that the upstream cache tries to do a lookup - if there is no entry, then the downstream cache would perform the lookup itself. One architecture might have many in-network or geographically-local caches pointing at each other, getting the benefit of a shared memory pool and decreasing lookup times if any one of the group already has an answer in memory.

**Comment by rgacogne** [comment]
Asking the same incoming question to multiple backends is not going to happen, sorry.

**Comment by Bacto** [comment]
I use multiple backends but sometimes packets are lost or DNS servers are slow to respond.
I think it's something part of the internet and we can't rely on it and should always have a plan B.

Asking multiple backends at the same time or having the ability to ask another backend in case of a failure/timeout would be really great to improve realibility.

I didn't found a way to do this in dnsdist. Maybe I missed something?

**Comment by Habbie** [comment]
Hello Adrien,

no, this is not possible in dnsdist. Sorry.

**Comment by Bacto** [comment]
Thanks for your reply @Habbie. I hope I'll find a solution :)

**Comment by franklouwers** [comment]
I have a different use-case for this request:

- We know that badly configured zones are out there, yet that's not changing,
- We know that different dns-software vendors work around those bugs differently
- We know that dns-flagdays were supposed to streamline that, but except for the first one, the dnsflag days can be categorized as a failure
- We know that PowerDNS refuses to work around those bugs (not claiming they should)
- So the only way to run a dns service nowadays for a large number of diverse eyeballs, is to run multiple DNS server brands

So it would be great to be able to run a set of vendor-X (preferably PowerDNS) servers to perform the bulk of the work, yet to be able to divert SERVFAIL results to a pool of vendor-Y servers (eg Bind or Unbound) to handle those rfc-violating-yet-existing-and-resolved-perfectly-fine-by-the-quads domains. 

To do that, a way to handle SERVFAIL results in rule / lua-code and to resend them to a separate pool would be the answer.

**Comment by johnhtodd** [comment]
I was thinking about this earlier, though Remi succinctly states the PowerDNS position higher in this ticket about parallel queries.  Another terrifyingly ugly way to do this might be to "tee" queries into a loopback address, which is configured to listen but send queries to a different pool but use the same cache.  This would still probably fail for the first query, but if the second query was able to "displace" the NXDOMAIN or SERVFAIL that resulted from the first query, then at least a useful answer would find its way into the cache.  Instrumenting what percentage of things were answered by what version of software would be "interesting" and it would also naturally double the volume of queries coming out of your cluster.  I have tested none of this in any way - anyone who is brave enough to do so should put their results here.

Another way to do this is to look at the DNSTAP or PowerDNS-formatted protobuf output of dnsdist looking for SERVFAIL answers and writing a shim that sends them (again, same cache, different pool) to a different resolver backend.  If you end up writing one of those, let me know.  :-) This could also work for NXDOMAIN but that seems to be not useful.  You'd have to be careful to filter the inbound query stream to discount queries going to your secondary pool somehow (destination port?) otherwise it will self-feed.

**Comment by franklouwers** [comment]
@johnhtodd interesting approach. I was considering (maybe naively) to leverage the pdns-recursor's `postResolve()` hook, and perform a LUA dns query to another pool on SERVFAILs. Yes this will slow down SERVFAILs massively, but at the advantage of being able to resolve more broken domains.

**Comment by rgacogne** [comment]
> To do that, a way to handle SERVFAIL results in rule / lua-code and to resend them to a separate pool would be the answer.

The work I'm currently doing in preparation for 1.7, cross-protocol handling [1], might make that easier to implement. Still it's not on the top of my list of priorities so it would help a lot if someone else were interested in writing (parts of?) that code.

[1]: https://github.com/PowerDNS/pdns/pull/10338

**Comment by franklouwers** [comment]
Am willing to contribute $$ to increase priority. My customers (and thus me) are losing customers / money because of this. Unless we institute a dns-flag day where all the quads would agree that xarasoft.com.co. is so broken it shouldn't resolve, but I don't think this is going to happen...

**Comment by karelbilek** [comment]
Isn't this solved by #12388 and ready in 1.8.0?

**Comment by karelbilek** [comment]
However it seems like it's not possible to catch "timeouts" with addResponseAction/restart. Only servfails.

**Comment by hvisage** [comment]
I was looking at different reason for concurrent/parallel requests to "all" the backends:

 keeping the backend/upstreams all "hot", in a the whash/chash you have a failure/move, and the "cold" caches needs to warm up from the lost host cache's data. In the round robin/nextavailble/etc.  the caches are luke warm, so several times slow responses

**Comment by rgacogne** [comment]
> However it seems like it's not possible to catch "timeouts" with addResponseAction/restart. Only servfails.

Note that we now have rules that are triggered on timeouts, see https://www.dnsdist.org/reference/rules-management.html#addTimeoutResponseAction
