### ISSUE TITLE
Avoid using UDP source port 11211

### ISSUE THREAD

**Issue by job** [PowerDNS/pdns#6321]
- Program: Recursor
- Issue type: Feature request

### Short description

The recursor uses `1025 + dns_random(64510)` as ephemeral port - but UDP/11211 is now tainted due to the open memcached problem and in tons of people's rate-limiters and ACLs. Perhaps that source port should simply be avoided.

**Comment by majek** [comment]
In the mean time
```
sysctl -w net.ipv4.ip_local_reserved_ports=11211
```

**Comment by ahupowerdns** [comment]
So I think we should do this since this question keeps coming up. In a more generic sense, we should be able to set the range of ports we use, and then have a list of ports we don't use. It is overkill to make this too generic so we could set 1024-2048,32768- etc. So I suggest something like min-udp-source-port, max-udp-source-port and avoid-udp-source-port=80,11211
