### ISSUE TITLE
PowerDNS Recursor accepts additional A,AAAA in answer section (with/without dnssec)

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns#6332]
- Program: Recursor
 - Issue type: Investigation

### Short description
https://indico.dns-oarc.net/event/28/session/11/contribution/46/material/slides/0.pdf mentions this. We should investigate if this is intentional and if we do the right thing with and without DNSSEC.

Video at https://youtu.be/bU6mL0AkbS8?t=2170

### Environment
 - Software version: 4.1.1

**Comment by pieterlexis** [comment]
Off the top off my head, we accept the records in the answer section and store it in the cache if it come from the right auth. If we don't validate the records we cache (because the client did not ask for the extra qtype), we will validate them later when they are retrieved from the cache (as the vState will be Indeterminate).
