### ISSUE TITLE
RPZ consumes ~2-3x expected memory after reloads

### ISSUE THREAD

**Issue by phonedph1** [PowerDNS/pdns#6607]
- Program: Recursor
 - Issue type: Bug report

### Short description
It appears as successive ```reload-lua-config``` or even IXFR/non-IXFR transfers eventually consume ~2-3x the memory on an idle recursor than the initial starting point. Below I could online reproduce 2x, but earlier today it was looking closer to 3x as 5 million had the staring point around 860MB.

### Environment

 - Operating system: Amazon "CentOS 6"
 - Software version: pdns-recursor-0.0.2148g156e381-1pdns.el6.x86_64
 - Software source: repo

### Steps to reproduce
1. ```lua-config-file=/etc/pdns-recursor/rpz.lua```
2.  
```
[root@ip-172-31-26-86 pdns-recursor]# cat rpz.lua
rpzFile("/tmp/zone", {policyName="test"})
[root@ip-172-31-26-86 pdns-recursor]# 
```
3. 
```[root@ip-172-31-26-86 pdns-recursor]# head /tmp/zone
example.rpz.		86400	IN	SOA	rpz. rpz. 2 10800 3600 604800 600
example.rpz.		86400	IN	NS	rpz.
example.rpz.		86400	IN	SOA	rpz. rpz. 2 10800 3600 604800 600
1.example.rpz. IN CNAME .
2.example.rpz. IN CNAME .
3.example.rpz. IN CNAME .
4.example.rpz. IN CNAME .
5.example.rpz. IN CNAME .
6.example.rpz. IN CNAME .
7.example.rpz. IN CNAME .
```

continue on to ```5000000``` entries.
4. ```rec_control reload-lua-zone``` wait until done (log message and CPU stabilize), repeat a few times.
### Expected behaviour
Memory usage expected to remain fairly stable around initial starting point.

### Actual behaviour
Appears to eventually end up consuming approx. 2-3x the initial starting point.

```
[root@ip-172-31-26-86 pdns-recursor]# service pdns-recursor restart
Stopping pdns-recursor:                                    [  OK  ]
Starting pdns-recursor:                                    [  OK  ]
[root@ip-172-31-26-86 pdns-recursor]# ps -eo rss,args | grep pdns
1485792 /usr/sbin/pdns_recursor --daemon
 2212 grep --color=auto pdns
[root@ip-172-31-26-86 pdns-recursor]# rec_control reload-lua-config
Fatal: Timeout waiting for answer from control channel
[root@ip-172-31-26-86 pdns-recursor]# ps -eo rss,args | grep pdns
2254632 /usr/sbin/pdns_recursor --daemon
 2208 grep --color=auto pdns
[root@ip-172-31-26-86 pdns-recursor]# rec_control reload-lua-config
Fatal: Timeout waiting for answer from control channel
[root@ip-172-31-26-86 pdns-recursor]# ps -eo rss,args | grep pdns
2954108 /usr/sbin/pdns_recursor --daemon
 2068 grep --color=auto pdns
[root@ip-172-31-26-86 pdns-recursor]# 
```

### Other information
valgrind spewed too many errors to be useful.

I am not sure this is really a "bug" as a few GB of memory usage for 5 million RPZ entries seems quite satisfactory as is, but I can only expect people will grow beyond this someday.

**Comment by rgacogne** [comment]
Can you tell us a bit more about the rest of your configuration, especially the number of threads, and what kind of traffic you are receiving during this test?

The way our `RPZ` zones are loaded is that all threads share the same reference-counted version of a zone. When a zone is updated, via `{A,I}XFR` or `rec_control reload-lua-config`, a new copy is made and both versions co-exist for a time. Each thread will eventually detect that a new version is available and switch to this new version, and only then all threads have switched will the first version be freed, because the reference counter is down to 0. But the worker threads only check if a new version is available when they need to apply the `RPZ` to an incoming query, so the two versions can co-exist in memory for a long time if there is very few incoming queries.

Of course it might also be a bug :-)

**Comment by phonedph1** [comment]
Thanks @rgacogne these are low-QPS caches with no queries within the RPZ that would be hitting them. I'll do further testing to see if some life-like traffic triggers it to be free'd.

**Comment by phonedph1** [comment]
So after observing our RPZ-based caches for a bit there doesn't seem to be an excessively high growth in memory usage. PowerDNS does seem to use a ridiculously low amount of memory until the next (non initial) RPZ fetch, and then it stays on par with what BIND uses to host the zones, so this seems reasonable. I'm going to close this until I have more valuable information to provide.
