### ISSUE TITLE
Allow backend HA

### ISSUE THREAD

**Issue by deezknuts** [PowerDNS/pdns#6732]
- Program: Authoritative
 - Issue type: Feature request 

### Short description

Provide HA backend support.  Allow PDNS authoritative server configured for 3 DB nodes in a Galera cluster to continue to work when one DB node is down.  Currently, when one DB node goes down, PDNS logs the error and does not resolve anymore.  It would be useful for PDNS to continue and use the remaining 2 DB servers in the DB cluster to resolve records.

### Environment

 - Operating system:  Centos 7
 - Software version:  4.0.3
 - Software source: 
Powerdns repo
### Steps to reproduce

1.   Configure PDNS to use multiple mysql backends that is in a cluster.  Normal state
2.   Down on DB node in the DB cluster
3.   PDNS logs disconnect w/ DB server and does not work anymore even if it has two remaining connections to the DB nodes. "Caught an exception instantiating a backend. Unable to connect to database: Can't connect to MySQL server on '<server>'

### Usecase

Allow PDNS to continue to work using the remaining DB server connections.

### Description

If the DB connection is lost,  query the remaining DB servers it current has.

**Comment by ahupowerdns** [comment]
Hello "deezknuts",

We have pondered this feature frequently but it turns out that being resilient to database backend failure is very hard. Failures are rarely clearcut and it may be hard to determine which backend actually works. For this reason, we prefer to fail if the backend is down, and recommend that you get your HA from having multiple PowerDNS servers listening to multiple backends - one will always be up.

If there is more we can do to be helpful for this scenario, please let us know, but internal HA for using multiple backends is not likely to happen any time soon.

**Comment by Habbie** [comment]
To add to that, this feature was once in development, but as @ahupowerdns says, indeed it is hard. When dnsdist matured, we decided that running multiple pdns auths behind a single dnsdist is a better approach.
