### ISSUE TITLE
PacketCache causes EDNS compliance testing failures

### ISSUE THREAD

**Issue by marka63** [PowerDNS/pdns#6806]
We (ISC) were asked to explain why consecutive test from the EDNS compliance testing tool produced different results.    https://ednscomp.isc.org/ednscomp

It looks like the EDNS version in the request is not being taken into account when looking for cached answers.

% echo ipfreely.ca | ./genreport 
ipfreely.ca. @159.203.83.173 (ns1.ipfreely.ca.): dns=ok edns=ok edns1=ok edns@512=ok ednsopt=ok edns1opt=ok do=ok ednsflags=ok optlist=ok,nsid signed=ok ednstcp=eof
% echo ipfreely.ca | ./genreport
ipfreely.ca. @159.203.83.173 (ns1.ipfreely.ca.): dns=ok edns=ok,nsid edns1=noerror,badversion,soa,nsid edns@512=ok ednsopt=ok,nsid edns1opt=noerror,badversion,soa,nsid do=ok ednsflags=ok,nsid optlist=ok,nsid signed=ok ednstcp=eof

After giving 3 possible causes (the second on being a buggy whole answer cache) we got back:

Neither case 1 or 3 are place. However after setting the PacketCache to null in PowerDNS, it now seems to return the correct result.

**Comment by Habbie** [comment]
Hi Mark,

thank you for the report. Indeed the packet cache is our 'full answer cache'.

4.0 (and earlier) will fail ednscomp this way, while appearing to be perfectly compliant under slower, human inspection. This was fixed in [4.1.0-rc1](https://doc.powerdns.com/authoritative/changelog/4.1.html#change-4.1.0-rc1):

> Hash the entire query in the packet cache, split caches. This makes the authoritative server pass the EDNS compliance test.

So I'm closing this.
