### ISSUE TITLE
dnsdist: option to give each rule a name

### ISSUE THREAD

**Issue by Jamesits** [PowerDNS/pdns#7332]
- Program: dnsdist 
 - Issue type: Feature request 

### Short description
Can there be an option to add a display name for `addAction` so the rule content (for example, `qname in 1.example.com., 2.example.com, ...`) won't be shown on the web portal?

### Usecase
I have an `addAction` call which matches >50000 domains. Dnsdist performs very well, but when I'm trying to open its web portal, my browser starts to stuck since all the domains are re-rendered once per 1-2 second.  

Here is a visualization of what happened: (note the vertical scroll bar)
![snipaste_2019-01-05_20-34-08](https://user-images.githubusercontent.com/1297257/50724506-4b874b80-1129-11e9-828e-4bf50cfda808.png)

### Description
Add a third argument to `addAction` as the rule's name so on web portal that name can be displayed not the rule content.

**Comment by rgacogne** [comment]
Would you mind trying passing `true` as a second parameter to `SuffixMatchNodeRule()`, as documented in [1]? It not exactly what you want since you won't get a name, but at least you should be able to load the page :)

[1]: https://dnsdist.org/rules-actions.html?highlight=suffixmatchnode#SuffixMatchNodeRule

**Comment by rootwyrm** [comment]
Adding myself onto this one as well, since I have the same problem, just at a *much* larger scale - one of my SMNRs has over 400,000 entries. However, bumping this one because I disagree with @Jamesits as to the approach.

I think it would make more sense to extend `newSuffixMatchNode()` which takes no arguments, with a `name` (str) argument which would serve as the arbitrary identifier. This would eliminate any behavior changes in `addAction()` and would simplify the display in the web interface I suspect.

As for the web interface side, I'm not the pickiest, but I think it should be very clear that it's an SMNR rule rather than a standard qname rule. Perhaps display it as `SuffixMatchNode in SuffixMatchNode:name()`?

**Comment by phonedph1** [comment]
Unless I read this too quickly this should work now, eg,  `addAction(AllRule(), NoneAction, {name="this rule does all the things but nothing"})` will show up in `showRules()` with the name in a column.

**Comment by rgacogne** [comment]
I believe you are right, this should be fixed since 1.6.0. Thanks!

**Comment by ClaudioRifo** [comment]
On 1.6.1 the name does not show on the Web GUi, and on showRules() it shows the name but also all the IPs.

**Comment by phonedph1** [comment]
Depending on how you are matching IPs you can quiet it. 

```
NetmaskGroupRule(nmg[, src[, quiet]])
Changed in version 1.4.0: quiet parameter added
```

but you are correct the name does not show in the web UI. It would need to be added to the html and `api/v1/servers/localhost` I think - the normal rules don't hit `someResponseRulesToJson` so it misses that piece.

**Comment by ClaudioRifo** [comment]
I'm actually doing:
addAction(AndRule{makeRule(PublicForwarders), MaxQPSIPRule(10)}, TCAction())

So i think i don't have a Quiet option.

**Comment by sriccio** [comment]
Hi,

I found this topic while looking for a way to display the rule's "name" in UI instead of the rule content for more clarity.

As a rule name can be set in option table, it could be great a plus that it could be used for display in UI.

For example:

```
addAction(
  AndRule({
    SuffixMatchNodeRule(spamhaus_free_list),
    RDRule()
  }),
  PoolAction("dnsbl"),
  {name="Spamhaus FREE"}) 
```

A quick look with fiddler shows that the name for response rules is returned in the json:

![image](https://github.com/PowerDNS/pdns/assets/5239282/92f416d3-1e16-466e-9d1c-013820dfbc9c)

But not for action rules:

![image](https://github.com/PowerDNS/pdns/assets/5239282/5e467183-6271-48e2-be02-ac30b4a16c38)

It would be great that it is returned also for action rules. That way it would only miss a slight mod of the html to display the name, I guess.

**Comment by rgacogne** [comment]
Good suggestion, now implemented in https://github.com/PowerDNS/pdns/pull/13335 !

**Comment by sriccio** [comment]
Hello @rgacogne,

Amazing. Thanks a lot! Works great :)

![image](https://github.com/PowerDNS/pdns/assets/5239282/e21743eb-eb04-43fb-ad9b-715f3b6b0661)
