### ISSUE TITLE
max-cache-entries and max-packet-cache-entries have no effect

### ISSUE THREAD

**Issue by aldem** [PowerDNS/pdns#7458]
- Program: Authoritative
 - Issue type: Bug report

### Short description
Looks like configuration parameters `max-cache-entries` and `max-packet-cache-entries` are either ignored or misbehaving. Even when set to low value (like 1000 entries), pdns actually ignores them, at least, according to statistics (`packetcache-size` and `query-cache-size`) and RAM usage (process consumed more than 1G or RAM despite cache size limited to 10000 entries).

### Environment

 - Operating system:  CentOS 7
 - Software version: pdns-4.1.6-1pdns.el7.x86_64
 - Software source: PowerDNS repository

### Steps to reproduce
1. Create relatively big set records
2. Set `max-cache-entries` and `max-packet-cache-entries`  to value significantly less than number of records
3. Query all records and observe that all of them are cached regardless of limit

### Expected behaviour
Configuration parameters `max-cache-entries` and `max-packet-cache-entries`  must actually define upper limit for number of cached entries.

### Actual behaviour
Configuration parameters `max-cache-entries` and `max-packet-cache-entries` are ignored. Not sure if this matters but backend is sqlite.

**Comment by rgacogne** [comment]
Thank you for this report!
It might not be clear from our documentation (sorry about that!) but these numbers are not hard limits, meaning that both caches are allowed to cache more entries than the limit, but the cache cleaning algorithm will then remove enough entries to make sure that we are back under the limit. 
Note however that we might stay over the limit for a while depending on your traffic, since the cache cleaning algorithm is run roughly every 30s, but only if we receive queries.
Would you mind checking if the number of entries in the caches go back to normal after a while?

**Comment by aldem** [comment]
Just checked - cache is not cleared at all (it is more than one hour, and at least 20 minutes since last query), number of cached entries has not changed (server is idling).

This "soft" limit is actually not really good idea - in constrained environment (limited RAM) it may kill process and there is no way to prevent it, and restarts are expensive.

It would be much better to be able to specify really hard limits.

**Comment by rgacogne** [comment]
Adding the 'backport to stable?' label since the milestone has been updated to auth-4.2.0-beta1.

**Comment by Habbie** [comment]
For now, I suggest setting `max-cache-entries` and `max-packet-cache-entries` way lower, so you have some headroom.

**Comment by Habbie** [comment]
Hello! Are you able to see if #8713 (for master) or #8736 (for 4.2.x) fixes this for you?

**Comment by Habbie** [comment]
Fixed in #8713 / #8736.
