### ISSUE TITLE
api: does rrset order in zone patch matter?

### ISSUE THREAD

**Issue by CSharpRU** [PowerDNS/pdns#7501]
- Program: Authoritative
 - Issue type: Bug report

### Short description

I have a zone with *.zone.com A record. I'm trying to patch zone to delete A record and add CNAME *.zone.com and API tells me "Conflicts with pre-existing non-CNAME RRset" within this request:
```
{
  "rrsets": [
    {
      "name": "*.zone.com.",
      "type": "CNAME",
      "ttl": 86400,
      "changetype": "REPLACE",
      "records": [
        {
          "content": "google.com.",
          "disabled": false
        }
      ]
    },
    {
      "name": "*.zone.com.",
      "type": "A",
      "ttl": 86400,
      "changetype": "DELETE",
      "records": []
    }
  ]
}
```
But in case with this request everything is fine:
```
{
  "rrsets": [
    {
      "name": "*.zone.com.",
      "type": "A",
      "ttl": 86400,
      "changetype": "DELETE",
      "records": []
    },
    {
      "name": "*.zone.com.",
      "type": "CNAME",
      "ttl": 86400,
      "changetype": "REPLACE",
      "records": [
        {
          "content": "google.com.",
          "disabled": false
        }
      ]
    }
  ]
}
```

### Environment

 - Operating system: CentOS 7
 - Software version: 4.1.6
 - Software source: Operating system repository

### Steps to reproduce

1. Pretty easy to reproduce.

### Expected behaviour

Zone is patched without conflicts.

### Actual behaviour

API returns "Conflicts with pre-existing non-CNAME RRset".

**Comment by rgacogne** [comment]
From my understanding of the documentation, which I agree is not perfectly explicit on this point, this is the intended behavior. The `replace` operation will delete "all existing RRs matching name and type" before creating the new ones. In that case the `CNAME` does not exist yet and is therefore not deleted, nor is the existing `A` because it's a different type. The insertion of the `CNAME` rightfully fails because there is already a different type present for this name.

**Comment by zeha** [comment]
This is as intended, and the order of the RRsets indeed matters for PATCH.
