### ISSUE TITLE
dnsdist: --config-check returns returncode 0 for non-existing config file

### ISSUE THREAD

**Issue by christofchen** [PowerDNS/pdns#7611]
- Program: dnsdist 
 - Issue type: Bug report

### Short description

dnsdist returns 0 as result for a config check of an non-existing file. 

I understand that an empty or nonexistent config file is syntactically valid for DNSDIST, but this is still a little bit surprising. 
My expectation was that explicitly checking a file which cannot be read would result in a non-zero return code.

 - Operating system: CentOS
 - Software version: dnsdist 1.3.3
 - Software source: PowerDNS repository

### Steps to reproduce

`dnsdist --check --config nonexistentfile; echo $?`

### Expected behaviour

Expectation: non-zero return code (because of "unable to read configuration from 'nonexistentfile').

### Actual behaviour

```
$ dnsdist --check --config nonexistentfile; echo $?
Unable to read configuration from 'nonexistentfile'
Configuration 'nonexistentfile' OK!
0
```
Note the ZERO returncode.

**Comment by rgacogne** [comment]
Thank you for reporting this!
This is easy enough to fix (preliminary work in https://github.com/rgacogne/pdns/tree/dnsdist-check-config) but since we use `--check-config` in our systemd unit file, among other places, I wonder if that might break some setups where the default configuration file does not exist.
