### ISSUE TITLE
recursor fails to use NS to resolve itself under forward-zones

### ISSUE THREAD

**Issue by hawken93** [PowerDNS/pdns#8106]
Hi,
I've gotten help from @Habbie on IRC and would like to report a bug with the way recursor handles a certain edgecase.
I don't really know how to describe the issue briefly, but I hope the appendices will help you understand.

 - Program: Recursor
 - Issue type: Bug report

### Short description

My suspicion is that recursor doesn't put the records from the additional section in the cache, but I don't know.

I would like to refer to the steps in the "actual behavior" section below :)

### Environment

 - Operating system:  debian 10 (buster)
 - Software version:  4.1.11 (but tested 4.2 and master also)
 - Software source: operating system repo for 4.1.11, powerdns repo for 4.2 and master

### Steps to reproduce

* A recursor forwards the zone "vpn" to an authorative server
* the vpn zone contains the following records:
  * router.blu.vpn A 10.159.1.1
  * blu.vpn NS router.blu.vpn
* router.blu.vpn is an authorative server for the zone blu.vpn and also contains
  * router.blu.vpn A 10.159.1.1

### Expected behaviour

1. recursor sends the query to the hardcoded nameserver (authorative for the vpn zone)
2. The authorative server sends back authorative: blu.vpn NS router.blu.vpn and additional: router.blu.vpn A 10.159.1.1
3. recursor puts the A record in the cache
4a. recursor sees the record in the cache and returns it to the client.
4b. recursor decides to ask the nameserver about itself, using the A record in the cache to contact it
5b. recursor contacts router.blu.vpn, gets the A record and returns this to the client

### Actual behaviour

1. recursor sends the query to the hardcoded nameserver that contains the vpn zone
2. the authorative server sends blu.vpn NS router.blu.vpn in the authority section and router.blu.vpn A 10.159.1.1 in the additional section
3. recursor sees this and figures out that it is being asked to ask the nameserver about itself, figures out that this should be in the cache already
4. Somehow it is not in the cache so it asks the vpn. server again and gets the same answer
5. This fails, recursor gives up and gives back SERVFAIL to the client

### Other information

* 4.1.0-rc2 was tested by @Habbie (version before #2758) and notes that this version fails even earlier
* I'd like to attach IRC logs from the help that Habbie gave me, it provides extra insight.
https://gist.github.com/hawken93/14e529e50c5e10f2002891a10dad3032 + give an extra thanks, this was very helpful and the attitude positive :)

my configuration:
* https://gist.github.com/hawken93/9747cad5172bd43f9da9d43c838c8f8d conf
* https://gist.github.com/hawken93/340becba338f95d4aabd86d2e7e46c42 lua conf

my trace:
* https://gist.github.com/hawken93/6e61e698818b581d60001347e70a316d

here is a trace for matrix.blu.vpn. This resolves correctly
* https://gist.github.com/hawken93/7f7fd606443ac2b1f183437a36cacce5

**Comment by omoerbeek** [comment]
I analyzed this a bit. Note that I consequently use `blue` where the report used `blu`.
After the query is done, the cache does contain a correct `router.blue.vpn` A record.

But AFAIKS the recursor does not consult the cache here to resolve the name of the NS record, instead it forwards the query according to its config. It does get a result, but it only looks at the answer records and not at the additional record(s) in this case. Since the A we want (to get the IP address of the delegated zone NS) is in the additional section, it does not get processed.

If  I apply the diff below I do get a proper resolve. But be warned: this is probably not the right solution, it helps to understand what is going on.

```diff --git a/pdns/syncres.cc b/pdns/syncres.cc
index 2750b4d62..bfc5b093a 100644
--- a/pdns/syncres.cc
+++ b/pdns/syncres.cc
@@ -753,7 +753,7 @@ int SyncRes::doResolveNoQNameMinimization(const DNSName &qname, const QType &qty
           // filter out the good stuff from lwr.result()
           if (res == 1) {
             for(const auto& rec : lwr.d_records) {
-              if(rec.d_place == DNSResourceRecord::ANSWER)
+              if(rec.d_place == DNSResourceRecord::ANSWER || rec.d_place == DNSResourceRecord::ADDITIONAL)
                 ret.push_back(rec);
             }
             return 0;
```

**Comment by hawken93** [comment]
@omoerbeek first of all, thanks for looking at this :)


When I reread my description, I notice that it doesn't really say what exact query I have issues with, so I wanted to add that the exact query is:
`router.blu.vpn A?`

I still don't understand why it doesn't forward the query to the name server that owns the zone to get an authorative answer. But I can see a possible explanation wherein the code figures that the nameserver of the parent zone seems to have glue, so this nameserver should be able to provide the answer so we will ask it again. However as @omoerbeek noted, it doesn't matter how many times if asks if it is going to ignore the `additional` section. And it also looks a bit more messy in the logs, so I don't really know why it doesn't ask the owner of that zone.

I'm still learning though, and I don't know how a resolver is ideally going to solve this, neither how this codebase is thinking :)

If you need me to provide any more information, don't hesitate to hilight me :)

**Comment by omoerbeek** [comment]
The problem query is indeed router.blu.vpn A?, I figured that out from your initial description.

The logic of forwarding is a bit twitched and limited. It does not implement the full algorithm to handle delegation. If you read the docs very stritcly, it is even documented: the forward target should be an authoritative NS for the zone. In the test case it is not, since it delegates to a different NS for the subdomain.

To explain what is happening:

The code sees that it need to forward since the the qname is in the vpn domain. The target answers not with answer records, but with a delegation in the auth section. But the current code only looks at records in the answer section which contains only an NS record. That means that the NS name cannot be resolved via an A record to an IP, so the whole query is aborted.

My draft PR associated with this issue an non-aa answer as non-fatal and continues with consulting the cache.

I must say that I do not completely understand why the forwarding case is handled before looking at the cache.  At least the logging is confusing, since it says to consult to cache only but ends up in a forwarding-only case.

**Comment by omoerbeek** [comment]
There have been changes in this area the lastest release (4.4). Can you retest if this is still relevant?

**Comment by omoerbeek** [comment]
Closed for lack of activity.
