### ISSUE TITLE
recursor servfail every few days

### ISSUE THREAD

**Issue by tmanninger** [PowerDNS/pdns#8160]
- Program: Recursor
 - Issue type: Bug report
### Short description
I am using powerdns recursor with some forward-zones configured. All forward-zones works correctly exptected one, which talk to a local dns service named consul, see https://www.consul.io/docs/agent/dns.html

rescursor config [line:]
`forward-zones= ......... consul=127.0.0.1:8600`

Basically, the consul forward-zone works fine, but all few days the recursor returns SERVFAIL as response for a single domain (for about 15 - 70 seconds). While the recursor returns SERVFAIL, i can query the consul service directly without any error:
`dig +short -p 8600 esh.xdb.service.consul @127.0.0.1`

rescursor log:

> Aug 04 16:20:57 2 [59786952/1] question for 'esh.xdb.service.consul|A' from 10.30.9.6
> Aug 04 16:20:57 [59786952] esh.xdb.service.consul: Wants DNSSEC processing in query for A
> Aug 04 16:20:57 [59786952] esh.xdb.service.consul: Looking for CNAME cache hit of 'esh.xdb.service.consul|CNAME'
> Aug 04 16:20:57 [59786952] esh.xdb.service.consul: No CNAME cache hit of 'esh.xdb.service.consul|CNAME' found
> Aug 04 16:20:57 [59786952] esh.xdb.service.consul: No cache hit for 'esh.xdb.service.consul|A', trying to find an appropriate NS record
> Aug 04 16:20:57 [59786952] esh.xdb.service.consul: Cache consultations done, have 1 NS to contact
> Aug 04 16:20:57 [59786952] esh.xdb.service.consul.: Nameservers: <empty>(0.00ms)
> Aug 04 16:20:57 [59786952] esh.xdb.service.consul: Domain has hardcoded nameserver
> Aug 04 16:20:57 [59786952] esh.xdb.service.consul: Resolved 'consul' NS (empty) to: 127.0.0.1
> Aug 04 16:20:57 [59786952] esh.xdb.service.consul: Trying IP 127.0.0.1:8600, asking 'esh.xdb.service.consul|A'
> Aug 04 16:20:57 [59786952] esh.xdb.service.consul: query throttled
> Aug 04 16:20:57 [59786952] esh.xdb.service.consul: Failed to resolve via any of the 1 offered NS at level 'consul'
> Aug 04 16:20:57 [59786952] esh.xdb.service.consul: failed (res=-1)

All other domain queries to this backend continues to work while one domain returns SERVFAIL. 

I attached a wireshark file, in which you can see, that the zone backend "consul" returns an correct dns response, but recursor returns a SERVFAIL
[powerdns_consul_servfail_marked.pcapng.zip](https://github.com/PowerDNS/pdns/files/3467387/powerdns_consul_servfail_marked.pcapng.zip)
The first 4 packets shows a working response.
The next 4 packets show a correct consul response, but a recursor SERVFAIL.

### Environment

 - Operating system: Debian 9
 - Software version: 4.0.4-1+deb9u4
 - Software source: Operating system repository

### Steps to reproduce
I cannot reproduce this bug, it occurs every 3-7 days for 15-70 seconds.

### Other information

recursor configuration:
`allow-from=127.0.0.1/32, 10.30.0.0/16
config-dir=/etc/powerdns
forward-zones=in.vault.zone=xxxx, xxxx, xxxx, xxxx, stag.vault.zone=10.31.73.18;10.31.73.19, consul=127.0.0.1:8600
local-address=127.0.0.1,10.30.9.5,10.30.9.10
packetcache-servfail-ttl=5
setgid=pdns
setuid=pdns
version-string=confidential`

**Comment by rgacogne** [comment]
The line

```
Aug 04 16:20:57 [59786952] esh.xdb.service.consul: query throttled
```

indicates that we encountered too many failures with this server before, so we decided to stop using it for a while (note that this state is per-thread, which means that one thread could keep sending query to it while others don't, in case you are using more than one thread).
Unfortunately we don't know what happened before from this trace, would you happen to have the logs still around, by any chance?

Note that 4.0.4 is quite old, I'm not aware of any bug related to your issue fixed in more recent versions but you might want to upgrade nevertheless. We provide packages at https://repo.powerdns.com
In particular, 4.2.0 introduced a new setting [1] that you could use to instruct the recursor never to throttle your consul server.

[1]: https://docs.powerdns.com/recursor/settings.html#dont-throttle-netmasks

**Comment by tmanninger** [comment]
I have wireshark dump before and after the error. I this dump i can see, that the consul backend never fails (also returns the corrent dns response).
After 15 seconds, recursor retries to resolv 'esh.xdb.service.consul' and it fails. In my wireshark dump i can see, that consul returns the correct response, but recursor returns SERVFAIL.

consul always returns all responses with a ttl of 0 seconds, could be this a problem?

**Comment by omoerbeek** [comment]
> consul always returns all responses with a ttl of 0 seconds, could be this a problem?

yes, that might very well be related. Maybe try playing with https://doc.powerdns.com/recursor/settings.html#minimum-ttl-override. Wondering why a server would return TTL 0...

**Comment by tmanninger** [comment]
Since the upgrade to 4.2, the problem has not occurred again.

I think, the upgrade fixed the problem.

**Comment by lethargosapatheia** [comment]
In my case the problem was related strictly to DNSSEC. The queries are for an internal domain and the answers from consul were all correct, but recursor would send DNSSEC queries starting with the root hints. Disabling DNSSEC altogether (not recommended) solves this issue.
I'm trying to find a way of disabling it only for my internal domain, but I could find only the global `dnssec` directive: https://docs.powerdns.com/recursor/settings.html#dnssec

**Comment by omoerbeek** [comment]
Read the "Important" part of https://docs.powerdns.com/recursor/settings.html#forward-zones

**Comment by rgacogne** [comment]
> It's hard to understand why a simple solution like disabling dnssec per domain doesn't exist.

That's exactly what a negative trust anchor does, as explained in the documentation.

**Comment by lethargosapatheia** [comment]
I have to say that documentation lacks a lot, first of all. I needed around 4-5 days to configure replication between two authoritative servers with a postgresql database, because... everything is fragmented. I've come across random example on the internet that used mysql that helped me much more than the official documentation, so 'explained in the documentation' can hardly be a final argument :)

So having to run a lua script to do something as basic as that (which corresponds to two lines in unbound and one command in bind) after all this experience is rather discouraging, I have to say.
