### ISSUE TITLE
Please add support for the APL RR (RFC3123)

### ISSUE THREAD

**Issue by csch42** [PowerDNS/pdns#8379]
Hello and thanks for the great product!!!

The APL ([RFC 3123](https://tools.ietf.org/html/rfc3123)) RR type has lived a quiet life so far, ever since it was conceived in 2001, but I recently saw some applications, one of which I am particularly interested in:

ISC's proposal for [Catalog Zones](https://tools.ietf.org/id/draft-muks-dnsop-dns-catalog-zones-04.html), which currently attempts to mature through the IETF make (good) use of APL records.

I know, APL RRs are somewhat tricky and bear a fancy syntax too, but what would it take to have them supported in PDNS?

Thanks!

**Comment by Habbie** [comment]
> what would it take to have them supported in PDNS?

A patch submitted by a third party (such as yourself) seems like the most feasible path forward at this point.

**Comment by Habbie** [comment]
Whoever writes this patch may benefit from a brief look at pdns/ednssubnet.cc, or even some stealing or moving of some of the code in there.

**Comment by stbuehler** [comment]
An `RDATA` format that can be extended by future revisions but doesn't define a text representation for those extensions is gonna be difficult to implement properly.  Ideally (imho) one would use the generic `TYPE.. # <len> <hex>` representation for unknown variants, but last time I checked pdns didn't support that.

**Comment by Habbie** [comment]
>  Ideally (imho) one would use the generic `TYPE.. # <len> <hex>` representation for unknown variants, but last time I checked pdns didn't support that.

pdns does support it, but with some annoying restrictions, like 'if you upgrade to a newer version that supports the type, your generic syntax records will start SERVFAILing' (#804)

**Comment by stbuehler** [comment]
Ack.

While I said in https://github.com/PowerDNS/pdns/issues/804#issuecomment-354168484:
> generic RDATA texts \# <nn> <hex> are not invalid for normal interpretations (the obvious example being TXT)

for specific types the generic representation might be invalid (if interpreted as "normal" represenation).

So far APL text representations start with the number of the address family of the first entry (or are empty), so `\#` is likely to be an invalid prefix in future extensions, and for `APL` the generic representation can be used in in case the list contains an unknown address family. (I'd still prefer if pdns could handle the generic representation in all types if the generic `TYPE..` representation is used instead of the mnemonic.)

`dig` uses the generic representation if the list contains an unknown address family:

```
unknown.type42.example.org.       3600 IN APL \# 4 FFFF0000
unknown-mixed.type42.example.org. 3600 IN APL \# 8 00010000FFFF0000
```

And dig will fail with `;; Warning: Message parser reports malformed message packet.` if the data doesn't fit the required binary structure, and with `;; Got bad packet: FORMERR` if `AFDPART` contains trailing zero octets (no matter the address family, even if only the specified families require no trailing zero octets, and the generic format doesn't. Not sure if this is the right way to go.).

While `DNSSEC` is used as argument to require unique (i.e. shortest possible) encoding in the known address families, it doesn't require normalization afaict.

Also the RFC doesn't require that the address only contains `PREFIX` significant bits, so `APL 1:192.168.1.1/16` is actually valid (and `dig` seems to support this too).
