### ISSUE TITLE
dnsdist: Improve LogAction

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#8390]
- Program:  dnsdist 
 - Issue type: Feature request

### Short description
1/ The binary format should have at least:
- timestamps
- query IDs
- remote address (probably prefixed so we know how long it is, or something)

2/ We should be able to log to stdout in text format in non-verbose mode.

3/ It would be nice to be able to insert a timestamp in the text format in case we log to a file.

**Comment by paddg** [comment]
With regard to encrypted DNS, it is maybe worth to consider debugging problems with DNS clients. For example, how to analyze DNS packet protocol details? Before encryption we had pcap and tools like Wireshark. But how to look at DNS protocol details on the endpoint if traffic is encrypted?

**Comment by rgacogne** [comment]
For the record, since a discussion on that topic followed on our IRC channel, `dnstap` or in a lesser measure our own protobuf format might be good solutions when you need to look at the packet in clear-text.

**Comment by paddg** [comment]
Yes. I tried it with the help from @Habbie and @rgacogne. Thank you! Turning on local dnstap logging works this way for example:
```
dnstap=newFrameStreamUnixLogger("/var/run/dnsdist/dnsdist.dnstap")
addResponseAction(AllRule(),DnstapLogResponseAction("dns",dnstap))
```
In order to create the needed socket you have to start a fstrm_capture with the proper permissions:
```
mkdir -p /var/run/dnsdist/ /var/log/dnsdist/
chown dnsdist.dnsdist /var/run/dnsdist/ /var/log/dnsdist/

su - dnsdist -s /bin/bash -c "fstrm_capture \
-t protobuf:dnstap.Dnstap \
-u /var/run/dnsdist/dnsdist.dnstap \
-w /var/log/dnsdist/fstrm.tap"
```
Now you can look into the packets details with this command for example:
`dnstap-read -y /var/log/dnsdist/fstrm.tap`

Very nice.

Also, thank you @jpmens for your very useful dnstap [writeup](https://jpmens.net/2017/09/11/dns-query-response-logging-with-dnstap/)!
