### ISSUE TITLE
rec: Support proxy protocol for incoming queries

### ISSUE THREAD

**Issue by rgacogne** [PowerDNS/pdns#8402]
- Program: Recursor
 - Issue type: Feature request

### Short description
Basically support the other side of #8401, to be able to provide the original source and destination addresses and ports, as well as any TLVs data, to the `Lua` hooks, including the `gettag` ones. 

We might also want to be able to rewrite the source and destination address passed to the rest of the code, as we do today for XPF.

We should be careful to only accept these from whitelisted hosts.

**Comment by M4t7e** [comment]
I like the idea of providing more information between the fronted (dnsdist) and the backend. I have played a lot with XPF and ECS. It is sometimes very useful, but sometimes a big pain point in the recursor, due to the packet cache and the definition of the outgoing ECS value. Today, there are only global options for configuring the ECS. Could it be possible in the `gettag` hook to dynamically define the ECS value as an additional `string` or `netmask` return value? Then you have maximum control over the ECS without destroying the packet cache. Examples:
- Use a parameter from the proxy protocol as ECS
- Use the incoming ECS as outgoing ECS
- Use a XPF value as ECS (e.g. XPF source IP)
- Use the source IP as ECS
- Dynamically swap the full ECS value with another value from the geographic area of the user or DNS resolver to increase user privacy
- Dynamically change the source prefix length of the ECS
- Don't send an outgoing ECS (`nil` value?)
- Define the ECS based on user specific settings (switch location, send fewer ECS bits, disable ECS, ...)
- etc.

It can also be useful to provide additional information, such as tags from the frontend to the backend, if the proxy protocol supports this. Then you can make use of it in the `gettag` hook and for example provide the information to other hooks with the `data` return value.

**Comment by zeha** [comment]
#8874?

**Comment by Habbie** [comment]
I'd say so, @rgacogne ?

**Comment by rgacogne** [comment]
Indeed!
