### ISSUE TITLE
Removing EDNS workarounds

### ISSUE THREAD

**Issue by jsha** [PowerDNS/pdns#8724]
- Program: Recursor
 - Issue type: Bug report

### Short description
I was reading the recursor source and noticed that it still contains EDNS fallback code: https://github.com/PowerDNS/pdns/blob/d650d4b76b2bd7280b96153f9cd1f7b9becf1a84/pdns/syncres.cc#L543-L561

I was surprised to see this, because the [2019 DNS Flag Day](https://dnsflagday.net/2019/) was about removing such EDNS fallback code. PowerDNS was listed as a supporter, and has a blog post announcing the planned change:
https://blog.powerdns.com/2018/03/22/removing-edns-workarounds/

I've looked through issues and Changelogs, and haven't been able to find a note about removing this code. Is that still the plan?

### Environment

No particular environment, just reading the source code.

### Steps to reproduce

Reading source at https://github.com/PowerDNS/pdns/blob/d650d4b76b2bd7280b96153f9cd1f7b9becf1a84/pdns/syncres.cc#L543-L561; compare to blog post and DNS flag day page.

**Comment by phonedph1** [comment]
https://github.com/PowerDNS/pdns/pull/6628

**Comment by Habbie** [comment]
Thanks @phonedph1.

Indeed, the removal of EDNS workarounds is in #6628. Not all state transitions in that comment block are valid since that PR. We somehow managed to, indeed, completely leave that out of the changelog, except for the linked blog post https://blog.powerdns.com/2019/02/01/changes-in-the-powerdns-recursor-4-2-0/

This is the second time in a few weeks we've gotten this question about our change log. Leaving this ticket open to deal with that!
