### ISSUE TITLE
dnsdist: setWebserverConfig({apikey="..."}) has no effect

### ISSUE THREAD

**Issue by peterthomassen** [PowerDNS/pdns#8797]
- Program: dnsdist
 - Issue type: Bug report

### Short description
According to the docs, the dnsdist webserver API key can be changed with `setWebserverConfig({apikey="..."})`. However, it seems to have no effect. (Setting `password` this way works.)

### Environment
 - Operating system: Debian stretch
 - Software version: 1.4.0
 - Software source: PowerDNS repository

### Steps to reproduce
1. `webserver("127.0.0.1:8083", "supersecretpassword", "supersecretAPIkey")`
2. `setWebserverConfig({apikey="foobar"})`
3. `curl -H 'X-API-Key: foobar' http://127.0.0.1:8083/metrics`

### Expected behaviour
200 response

### Actual behaviour
401 response

Also, disabling the API key by setting an empty string is not possible (although documented).

### Other information
I wonder why there is a password and an API key? Also, why can the password not be disabled, but the API key can?

**Comment by rgacogne** [comment]
> setWebserverConfig({apikey="foobar"})

There was a mistake in the documentation, it's `apiKey` not `apikey`, sorry about that :-/

**Comment by rgacogne** [comment]
> I wonder why there is a password and an API key? 

They don't give access to exactly the same HTTP resources. Only the `/api/v1/servers/localhost` part of the API is allowed to password users.

> Also, why can the password not be disabled, but the API key can?

At some point we decided that it might make sense to add access to the HTTP status page (which is mostly was the password is about) without a password since it's read-only and having to enter a password every time might be annoying. The API is not designed to be used in a browser so there was really not point in being able to access it without a password. It also allows to alter some parts of the configuration.

**Comment by peterthomassen** [comment]
Thanks for the fix!

> > I wonder why there is a password and an API key?
> 
> They don't give access to exactly the same HTTP resources. Only the `/api/v1/servers/localhost` part of the API is allowed to password users.

I could not find that information in the documentation. Maybe I missed it somewhere. So, the API key gives access to everything, and the password just to that path?
