### ISSUE TITLE
Too many Duplicate record found in rrset and disallow double dot and whitespace

### ISSUE THREAD

**Issue by mekbuk** [PowerDNS/pdns#8860]
- Program: Authoritative 
 - Issue type: Bug report

### Short description

1, to many error Duplicate record found in rrset
2. too many whitespace, double dot (..) etc, how to disallow this?

### Environment

 - Operating system: Centos7 
 - Software version: 4.1.11
 - Software source: using CentOS repository

**Comment by Habbie** [comment]
Hello,

I'm afraid we do not understand what you mean. Can you show what you did, what happened, and what you expected to happen instead?

Or, alternatively, please find us on IRC, the details are at https://www.powerdns.com/opensource.html

**Comment by mekbuk** [comment]
1. too many error Duplicate record found in rrset mean records got 2 records NS 
2. same issue like this [https://mailman.powerdns.com/pipermail/pdns-users/2016-January/023942.html](url)

**Comment by Habbie** [comment]
Ah, so you're asking how to prevent the type of errors that `check-zone` spots. The answer is to use our [REST API](https://doc.powerdns.com/authoritative/http-api/index.html) instead of inserting data directly into the database through SQL.

As this is a not bug report, I'm closing this ticket. If you have further questions, please find us on IRC or the pdns-users mailinglists. Details are on https://www.powerdns.com/opensource.html
