### ISSUE TITLE
A successful PATCH returns entire list of rrsets (and not only 204 No Content)

### ISSUE THREAD

**Issue by olleharstedt** [PowerDNS/pdns#8920]
- Program: Authoritative
 - Issue type: Bug report

### Short description

A successful PATCH returns entire list of rrsets, and not only 204 No Content, as documented here: https://doc.powerdns.com/md/httpapi/api_spec/#url-apiv1serversserver95idzones

### Environment

 - Operating system: Ubuntu
 - Software version: 4.0.0-alpha2
 - Software source: Operating system repository

### Steps to reproduce

1. curl a PATCH request with rrsets, as documented here: https://doc.powerdns.com/md/httpapi/api_spec/#url-apiv1serversserver95idzones

### Expected behaviour

I'd expect an empty response with "204 No Content".

### Actual behaviour

Entire list of rrsets (BIG response).

### Other information

Let me know if I missed anything in the documentation or configuration. Maybe it's an easy setting?

**Comment by Habbie** [comment]
> Software version: 4.0.0-alpha2

You are running an unsupported prerelease. Can you please try upgrading to 4.2.1 or 4.3.0-beta2 and try again? https://repo.powerdns.com/ has packages for you. Please check https://doc.powerdns.com/authoritative/upgrading.html for any relevant (schema) changes to go with that upgrade. I don't recall us having fixed it since, but if you can check, that would be great.

**Comment by olleharstedt** [comment]
Yes, this fixed the issue. Thank you!

**Comment by Habbie** [comment]
Thank you for reporting back!
