### ISSUE TITLE
dnsdist: Wildcard path on DoH endpoint

### ISSUE THREAD

**Issue by mzealey** [PowerDNS/pdns#8980]
- Program: dnsdist
 - Issue type: Feature request

### Short description
Currently DoH implementation only supports a single fixed path in the URL. We would like to be able to capture anything under that and process it in lua.

### Usecase
We want to give clients an individual link containing some unique id number like `https://doh.example.com/client/<id>`. Then we can use this to allow per-user configurations without resorting to custom EDNS options (which are unsupported in the JSON interface apparently). We would need to be able to manipulate the URL to extract the `<id>` field and put it into EDNS options for the backend pdns to pick up.

### Description

Suggested implementation:
1) Add a parameter to the DoH setup function called `allowSubpaths` (defaulting to `false`). This would say that anything under the specified endpoint path would be accepted, so we could specify URL as `https://doh.example.com/client/`.
2) Somehow pass this through to the action. In our case we'd write something in lua that had similar functionality to `MacAddrAction` or `ECSAction` to extract, encode and add the id to an EDNS option.

**Comment by rgacogne** [comment]
The HTTP path is already available to `Lua` rules and actions via `DNSQuestion::getHTTPPath()` [1], so it looks like the only thing you need is your first point. Since it was the default behaviour before https://github.com/PowerDNS/pdns/pull/8760, it should not be too hard to implement that option if someone cares enough.

[1]: https://dnsdist.org/reference/dq.html#DNSQuestion:getHTTPPath

**Comment by rgacogne** [comment]
Implemented in #9962.
