### ISSUE TITLE
PowerDNS returns empty response for response sizes exceeding 64k

### ISSUE THREAD

**Issue by tommyulfsparre** [PowerDNS/pdns#9201]
- Program: Authoritative 
 - Issue type: Bug report

### Short description

PowerDNS returns empty responses for size exceeding 64k

### Environment

 - Operating system: Ubuntu 18.04
 - Software version: 4.3.0 
 - Software source: 

### Steps to reproduce

1. Run PowerDNS with a Backend that returns a payload that exceeds 64k.
2. Do a query `dig _tcp.example.com -t srv @127.0.0.1`
3. Observer the response:
```
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.10.6 <<>> _tcp.example.com -t srv @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55583
;; flags: qr aa tc rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;_tcp.example.com.		IN	SRV

;; Query time: 10 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Jun 04 11:38:15 CEST 2020
;; MSG SIZE  rcvd: 45
```
### Expected behaviour
This might be the expected behaviour but previous version of PowerDNS would truncate the response to fit 64k. Running the same query on `4.1.1` yields a response with:

```
;; Truncated, retrying in TCP mode.

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> _tcp.example.com -t srv -p 5454 @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12013
;; flags: qr aa tc rd; QUERY: 1, ANSWER: 1799, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1200
;; QUESTION SECTION:
;_tcp.example.com.		IN	SRV

;; ANSWER SECTION:
<REDACTED>

;; Query time: 3286 msec
;; SERVER: 127.0.0.1#5454(127.0.0.1)
;; WHEN: Thu Jun 04 11:06:10 UTC 2020
;; MSG SIZE  rcvd: 65501
```
### Actual behaviour
Empty response.

### Other information
We could solve this in our custom backend but the problem is that we don't know the final size of the request as PowerDNS might fill in the additional section as well.

**Comment by Habbie** [comment]
The 4.1.1 behaviour is bad. The 4.3.0 behaviour is better, but SERVFAIL would be even better. We are not going back to partial responses, sorry.

**Comment by tommyulfsparre** [comment]
No worries, then we can take corrective actions on our side.

Out of curiosity why do you consider a partial response as bad and an empty better?

**Comment by Habbie** [comment]
The semantics of partial responses have been very badly defined, and interpretations of them has varied between DNS interpretations over the years. In practice, this means that any sane client will never look at the content of a response that has TC=1, because it does not know what it means.

(I understand that in your case, the client is your own software and the server is always PowerDNS, so you do in fact know what's happening, but that's quite a special case)

**Comment by tommyulfsparre** [comment]
Thanks for the explanation and the responsiveness in general. 

You are correct and we are painfully aware that this is a special case :).

**Comment by lepistone** [comment]
Hi! I read yet another time this old issue and there is still a point that confuses me.

As far as I understand, the TC flag is used to signal that the reply is larger than 512 bytes and the client must query again with TCP. In this context, I understand and agree with @Habbie 's reasoning: clients are expected to try again with TCP anyway, so the safest thing for them to do is to throw away any partial response obtained over UDP.

But @tommyulfsparre 's issue is different: it's about exceeding the limit for TCP packets, which is 64KB. There is no alternative to this, so the effect of an empty response here is immediately catastrophic and irrecoverable. In this context, things seem to have actually gone worse in 4.3.0, as @tommyulfsparre claimed.

This is the same context as @tommyulfsparre 's other issue #9199: for records that are already large (in this example, large SRV records used for service discovery), the removal of `do-ipv6-additional-processing` also made things worse because it's now easier to reach the limit with the Additional section.

I hope this makes more sense now, thanks!
