### ISSUE TITLE
dnsdist stops handling DoH after a while

### ISSUE THREAD

**Issue by krombel** [PowerDNS/pdns#9206]
- Program: dnsdist
 - Issue type: Bug report

### Short description
after a while dnsdist stops responding to DoH-Queries (while all other protocols continue to work)

### Environment
 - Operating system: debian buster
 - Software version: 1.5.0-rc2
 - Software source: PowerDNS repository

### Steps to reproduce
I am not sure. It happens when we run dnsdist for a while.

### Other information
Some stats of dnsdist directly:
https://stats.ffmuc.net/d/tlvoghcZk/doh-dot?orgId=1&from=1591373515179&to=1591376176006
The probably the most relevant graph: DNS queries/minute
![image](https://user-images.githubusercontent.com/11167142/83910764-679e7a80-a76b-11ea-8f11-cbd10d25ae8e.png)
Green: All requests; yellow DoHv4; blue DNSCrypt; ...
Note: I have two dedicated listeners for IPv4 and IPv6 and only the IPv4-Listener broke. The DoHv6 listener kept answering (but gets hit that low that you cannot really see it in the graph)

nginx (which is reverse proxying DoH) reports following stats:
![image](https://user-images.githubusercontent.com/11167142/83910147-543edf80-a76a-11ea-8014-729d56c4c5be.png)

`strace -p <PID_of_dnsdist> -o dnsdist_faulty.strace.txt -f`
[dnsdist_faulty.strace.txt](https://github.com/PowerDNS/pdns/files/4737823/dnsdist_faulty.strace.txt)
`gdb -p <PID_of_dnsdist> -x gdb-script --batch > dnsdist_faulty.gdb.txt` where gdb-script contains
`thread apply all bt full`:
[dnsdist_faulty.gdb.txt](https://github.com/PowerDNS/pdns/files/4737824/dnsdist_faulty.gdb.txt)

**Comment by rgacogne** [comment]
Leads that I investigated that seem to be dead ends:
- one thread stopping to work because of an exception not being handled: all threads are accounted for in GDB, nothing weird pops to mind ;
- the internal response socket pair getting full: the GDB trace shows a lot of threads in the process of writing to the response socket pair, which could have indicated that they are blocked because the buffer is full. The strace log does not confirm that, although it shows that some of the "new" DoH connections processed by h2o are in fact quite old and already closed on the OS side (`getpeername()` returns `ENOTCONN`), which seems to indicate that thread was indeed blocked for a short while, or at the very least completely overwhelmed. 

I'll keep investigating, and prepare a patch to make sure that we can't block if the internal pipe becomes full. I'll add a metric for that event as well.

**Comment by rgacogne** [comment]
I believe this issue was fixed by #9211 so I'm going to close this issue. Hopefully I won't have to re-open it later :-)
