### ISSUE TITLE
down 1 distributor thread when use distributor-threads mode v4.2.1

### ISSUE THREAD

**Issue by liwei0526vip** [PowerDNS/pdns#9257]
- Program: Recursor
 - Issue type: Bug report
 - Version: 4.2.1

### Short description

We are trying to use the distributor-thread method of pdns-recursor, configured with 3 distributor-threads, N worker threads, and ran for about 3 days, and found that distributor-thread died one of the threads, and some of the logs are very simple The message is below

```bash
any other exception in main:
```

### Environment
 - Operating system: CentOS7.3 kernel 3.10
 - Software version: 4.2.1

### Steps to reproduce

1. There is no stable way to reproduce, but there have been two problems so far

**Comment by omoerbeek** [comment]
Please share the config file.

**Comment by liwei0526vip** [comment]
#### my configuration information

```bash
allow-from=0.0.0.0/0,::/0
daemon=yes
disable-packetcache=yes
disable-syslog=no
dnssec=off
dont-query=127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32
edns-subnet-whitelist=xxxx.com.hk
log-timestamp=yes
loglevel=7
packetcache-servfail-ttl=1
pdns-distributes-queries=yes
processes=1
query-local-address6=::
quiet=off
reuseport=yes
statistics-interval=0
trace=off
use-incoming-edns-subnet=yes
webserver=no
non-local-bind=yes
api-key=changeme
threads=19
local-address=10.10.10.10,10.10.10.11,172.16.42.31,172.16.42.32,10.41.0.45,10.41.0.46,172.16.234.38,172.16.234.41,172.16.153.24,172.16.153.87
socket-dir=/usr/local/pdns-recursor.debug/sbin/
cpu-map=0=0 1=1 2=2 3=3 4=4 5=5 6=6 7=7 8=8 9=9 10=10 11=11 12=12 13=13 14=14 15=15 16=16 17=17 18=18 19=19
forward-zones-recurse=xxx.com.hk=x.x.x.x;x.x.x.x
logging-facility=0
distributor-threads=3
dont-throttle-netmasks=x.x.x.x x.x.x.x
```

@omoerbeek

**Comment by rgacogne** [comment]
That's weird because we don't have a lot of exceptions in the recursor not inheriting from either `PDNSException` or `std::exception`. I see these on master:
- `PolicyHitException`
- `ImmediateServFailException`
- `HttpException`

The first one did not exist in 4.2.x and your configuration seems to rule out the last one since the webserver is disabled (although you have `api-key` set, I wonder why).
Do I correctly understand that you don't see this issue if you have one distributor thread, without `distributor-threads=3`?
Also, out of curiosity, would you mind telling us why are you disabling the packet cache? It likely makes performance a lot worse than it could be.

**Comment by liwei0526vip** [comment]
Thanks your reply.  @rgacogne 

We are not using webserver. The api-key configuration is a bit redundant and can be deleted.

When we did not start the distributor before, the recursor runs without any problems. In order to improve the cache hit rate, we opened the distributor, but have not tried to set to 1 distributor thread for the time being, we directly opened 3 distributor thread, and then the above problem occurred.

In addition, the closure of packetcache is also to eliminate the impact of the servfail cache. It is currently closed only to test and verify some of our ideas.Later we will open packetcache

**Comment by rgacogne** [comment]
Thanks for the details! So you are not seeing this issue without the distributor, and it might also happen with only one distributor, we simply don't know that (yet?). We should investigate more and perhaps try to catch all types of exceptions there so we get more details..

**Comment by liwei0526vip** [comment]
@rgacogne   Thank you for your reply. We briefly looked at the relevant code. There are not many distributor-related codes. We plan to add some debugging information to the relevant code, hoping to be able to capture valid information when the problem is reproduced again. We are also looking forward to hearing your good news.

thank you very much

**Comment by Annih** [comment]
Hello @rgacogne 
We are also facing this issue, with sometimes way more than 1 distributor threads and it is greatly impacting the quality of our service as paquets seem to drop on the dead threads. That would be great if dead threads were cleaned up or even better replaced.

*Context*
It seems it happens when our network is globally in bad shape. It occurred massively during CenturyLink outage (2020-08-30).
Recently this kind of error were often surrounded by `Failed to update . records` as in #9416.

*Setup*
config:
```socket-dir=/var/run/recursor
setgid=pdns-recursor
setuid=pdns-recursor

allow-from=0.0.0.0/0
distributor-threads=32
dont-query=127.0.0.0/8
dont-throttle-netmasks=127.0.0.0/8,10.0.0.0/8
ecs-add-for=0.0.0.0/0,::
edns-outgoing-bufsize=8192
edns-subnet-whitelist=<redacted_domains&_subnets_list>
forward-zones-file=/etc/pdns-recursor/forward.conf
latency-statistic-size=1000000
local-address=0.0.0.0
local-port=53
lua-dns-script=/etc/pdns-recursor/recursor.lua
max-mthreads=4096
network-timeout=1500
packetcache-servfail-ttl=1
pdns-distributes-queries=yes
reuseport=yes
socket-mode=0660
stack-size=1000000
stats-ringbuffer-entries=1000000
threads=64
udp-source-port-avoid=5300,53000,8301
use-incoming-edns-subnet=yes```

We use *pdns-recursor 4.2.1* and forward 100+ zones to our various authoritatives servers.

We will try to use the recent pdns version with your exception handling and let you know.

**Comment by rgacogne** [comment]
It would be very good if you could upgrade, as it has likely been fixed in 4.2.4 by https://github.com/PowerDNS/pdns/pull/9306, 4.3.3 by https://github.com/PowerDNS/pdns/pull/9305.

**Comment by Annih** [comment]
Yep we'll try to directly upgrade to 4.4.0, thanks to your backports if we have difficulties we will be able to fallback on 4.2.4 or 4.3.5 :)

**Comment by omoerbeek** [comment]
Should be fixed. If  not, please re-open.
