### ISSUE TITLE
rec: www.dpaste.com sometimes bogus; insecure domain with apex CNAME

### ISSUE THREAD

**Issue by mnordhoff** [PowerDNS/pdns#9621]
- Program: Recursor
 - Issue type: Bug report

### Short description
`www.dpaste.com` sometimes validates as bogus. `dpaste.com` is always fine.

`dpaste.com` is an insecure domain with a zone apex `CNAME`, so none of it deserves to resolve, but the precise way in which it's failing is a bit odd.

I'm not sure what is required for it to be bogus, but it seems to involve learning the `dpaste.com` `SOA` record and/or the `CNAME` record.

### Environment
 - Operating system: Ubuntu 16.04 x86-64
 - Software version: 4.5.0~alpha0+master.190.g8446e56b8-1pdns.xenial and a couple slightly older builds
 - Software source: PowerDNS repository

### Steps to reproduce
1. Restart Recursor
2. `dig dpaste.com aaaa`
3. `dig www.dpaste.com`

### Expected behaviour
Consistent success or consistent failure.

### Actual behaviour
Some things are bogus and some things aren't depending on what steps you take.

### Other information
Unless I'm making a mistake, this isn't bogus:

1. `dig dpaste.com`
2. `dig www.dpaste.com`

Or this:

1. `dig dpaste.com soa`
2. `dig www.dpaste.com`

But this is:

1. `dig dpaste.com`
2. `dig dpaste.com soa`
3. `dig www.dpaste.com`

`trace-regex 'dpaste\.com\.$'` for `dig dpaste.com aaaa` and `dig www.dpaste.com`: https://mn0.us/ojCK

`recursor.conf`:
```
allow-from=127.0.0.0/8, ::1/128
allow-trust-anchor-query
carbon-ourname=clover_mattnordhoff_net
carbon-server=2a02:2770:8::2635:0:1
config-dir=/etc/powerdns
dnssec=validate
dnssec-log-bogus
hint-file=/usr/share/dns/root.hints
include-dir=/etc/powerdns/recursor.d
local-address=127.0.0.1, ::1
log-common-errors
lua-config-file=/etc/powerdns/recursor.lua
max-cache-ttl=172800
max-negative-ttl=10800
query-local-address=0.0.0.0, ::
quiet=yes
setgid=pdns
setuid=pdns
threads=1
udp-truncation-threshold=4096
```
(I know, I'm a Flag Day traitor!)

**Comment by mnordhoff** [comment]
; EDE: 10 (RRSIGs Missing)

**Comment by rgacogne** [comment]
```
Oct 18 22:55:16 clover pdns_recursor[16049]:   dpaste.com: Wants DNSSEC processing, auth data in query for DS
Oct 18 22:55:16 clover pdns_recursor[16049]:   dpaste.com: Looking for CNAME cache hit of 'dpaste.com|CNAME'
Oct 18 22:55:16 clover pdns_recursor[16049]:   dpaste.com: Found cache CNAME hit for 'dpaste.com|CNAME' to 'webapp-837091.pythonanywhere.com.', validation state is Insecure
Oct 18 22:55:16 clover pdns_recursor[16049]:   QM dpaste.com.|DS child=dpaste.com: Step3 Final resolve: No Error/1
Oct 18 22:55:16 clover pdns_recursor[16049]: dpaste.com: removing cut state for dpaste.com
```

that doesn't look good, we are removing the cut state when we should not. It leads us to miss the cut from Secure to Insecure, which explains the issue.

**Comment by rgacogne** [comment]
Introduced by https://github.com/PowerDNS/pdns/pull/9272

**Comment by rgacogne** [comment]
So we need to re-think that once again..

**Comment by rgacogne** [comment]
So the possibilities, when we are looking for a DS, are:
- there is a cut to a secure zone, and we have a signed DS from the parent. There might also be a CNAME in the child zone but we don't care about that (and I mean we don't want to know, not following the target is not enough) ;
- there is a cut to an insecure zone, and we have a secure denial from the parent. There might also be a CNAME in the child zone and we still don't care.
- there is no zone cut, and there we can have a `NXDOMAIN` or a `NODATA`, both with a secure denial, or a signed `CNAME`. 

And in that last case we actually do care about the `CNAME`, so we can't skip the CNAME lookup.
The current issue is happening because the current code is not correctly handling the second case since #9272, we see the `CNAME` and conclude that we are still in the same zone, which is not true.
